CREATE OR REPLACE VIEW VIEW_OA_INSTANCE AS
SELECT
   I.INS_ID,
   B.BUSITYPE_NAME,
   I.BUSITYPE_CODE,
   I.INS_NAME,
   I.INS_CODE,
   I.ACCEPT_TIME,
   I.ACCEPTER,
   I.ACCEPTER_ID,
   I.ORG_ID,
   I.FLOW_ID,
   I.DEF_ID,
   I.CC_FORM_INSTANCEID,
   I.BUSI_ID,
   I.LASTMODIFEDTIME,
   I.STATUS_CODE,
   C.ACTION_FORM,
   C.ACT_INSID,
   C.PROCESSID,
   C.ACTION_NAME,
   C.ACT_DEFID,
   C.ACTION_HANDERNAME,
   C.ACTION_HANDERID,
   C.TACHE_BEGIN_TIME,
   C.TACHE_END_TIME,
   C.IS_VALID,
   C.FLOW_ACTION_ID,
   I.Template_Id
FROM
   OA_FLOW_BUSITYPE B,
   OA_FLOW_INSTANCE I,
   OA_FLOW_INSWFACTION C
WHERE
   I.BUSITYPE_CODE = TRIM(B.BUSITYPE_CODE)
   AND I.INS_ID = C.INS_ID;

 
CREATE OR REPLACE FUNCTION OA_IS_BACK(V_INS_ID IN VARCHAR2,
                                      V_USER_NAME IN VARCHAR2)
--该函数用于查询，该用户是否有该流程实例的退回权限，如果是在办的并且上一步提交人是自己就有权限                                      
  RETURN VARCHAR2 AS
  ACT_INDEX VARCHAR2(50);
  T_STATUS_CODE VARCHAR2(50);
BEGIN
  SELECT MIN(ACT_INDEX)
    INTO ACT_INDEX
    FROM (SELECT ROW_NUMBER() OVER(ORDER BY W.TACHE_BEGIN_TIME DESC) ACT_INDEX,
                 W.ACTION_HANDERNAME
            FROM OA_FLOW_INSWFACTION W
           WHERE W.INS_ID = V_INS_ID
             AND W.IS_VALID = 'Y')
   WHERE ACTION_HANDERNAME = V_USER_NAME;
   --如果是2代表，上一步是自己提交
   IF ACT_INDEX = 2 THEN
   SELECT STATUS_CODE INTO T_STATUS_CODE FROM OA_FLOW_INSTANCE WHERE INS_ID = V_INS_ID;
       IF T_STATUS_CODE = '01' THEN
          RETURN 1;
       ELSE
         RETURN 0;
       END IF;
   ELSE
   RETURN 0;
   END IF;
END;
/

CREATE OR REPLACE FUNCTION OA_GETACTION_INDEX(V_INS_ID IN VARCHAR2,
                                              V_FLOW_ACTIONID IN VARCHAR2)
--根据流程实例ID，环节活动ID 按照时间查询出顺序。                                              
  RETURN VARCHAR2 AS
  ACT_INDEX VARCHAR2(50);
BEGIN
  SELECT ACT_INDEX
    INTO ACT_INDEX
    FROM (SELECT ROW_NUMBER() OVER(ORDER BY W.TACHE_BEGIN_TIME DESC) ACT_INDEX,
                 W.FLOW_ACTION_ID
            FROM OA_FLOW_INSWFACTION W
           WHERE W.INS_ID = V_INS_ID
             AND W.IS_VALID = 'Y')
   WHERE FLOW_ACTION_ID = V_FLOW_ACTIONID;  
  RETURN(ACT_INDEX);
END;
/

CREATE OR REPLACE FUNCTION OA_GETACTION_INDEX1(V_PROCESSID IN VARCHAR2,
                                              V_ACT_INSID IN VARCHAR2)
  RETURN VARCHAR2 AS
  ACT_INDEX VARCHAR2(50);
BEGIN
  SELECT ACT_INDEX
    INTO ACT_INDEX
    FROM (SELECT ROW_NUMBER() OVER(ORDER BY W.TACHE_BEGIN_TIME DESC) ACT_INDEX,
                 W.*
            FROM view_oa_instance W
           WHERE W.PROCESSID = V_PROCESSID AND W.ACTION_HANDERNAME IS NOT NULL
             AND W.IS_VALID = 'Y')
   WHERE ACT_INSID = V_ACT_INSID AND STATUS_CODE = '01';
  RETURN(ACT_INDEX);
END;
/