ALTER TABLE OA_SPLIT_LOG
   DROP CONSTRAINT FK_OA_SPLIT_REFERENCE_OA_SPLIT;

DROP TABLE OA_SPLIT_UNIT CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_SPLIT_UNIT                                         */
/*==============================================================*/
CREATE TABLE OA_SPLIT_UNIT 
(
   UNIT_ID              VARCHAR2(40)         NOT NULL,
   PARENT_ID            VARCHAR2(40),
   UNIT_NAME            VARCHAR2(200),
   REMARK               VARCHAR2(400),
   IS_VALID             VARCHAR2(1),
   GWCS_ORG_ID          VARCHAR2(40),
   CONSTRAINT PK_OA_SPLIT_UNIT PRIMARY KEY (UNIT_ID)
);

COMMENT ON TABLE OA_SPLIT_UNIT IS
'文件拆分单位维护';

COMMENT ON COLUMN OA_SPLIT_UNIT.UNIT_ID IS
'拆分单位ID';

COMMENT ON COLUMN OA_SPLIT_UNIT.PARENT_ID IS
'上级ID';

COMMENT ON COLUMN OA_SPLIT_UNIT.UNIT_NAME IS
'拆分单位名称';

COMMENT ON COLUMN OA_SPLIT_UNIT.REMARK IS
'备注';

COMMENT ON COLUMN OA_SPLIT_UNIT.IS_VALID IS
'是否有效';

COMMENT ON COLUMN OA_SPLIT_UNIT.GWCS_ORG_ID IS
'公文传输单位id，这个和公文传输对接';


ALTER TABLE OA_SPLIT_LOG
   DROP CONSTRAINT FK_OA_SPLIT_REFERENCE_OA_SPLIT;

DROP TABLE OA_SPLIT_LOG CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_SPLIT_LOG                                          */
/*==============================================================*/
CREATE TABLE OA_SPLIT_LOG 
(
   SPLIT_LOG_ID         VARCHAR2(40)         NOT NULL,
   UNIT_ID              VARCHAR2(40),
   BUSS_ID              VARCHAR2(40),
   PARENT_ID            VARCHAR2(40),
   FILE_NAME            VARCHAR2(200),
   FILE_PATH            VARCHAR2(500),
   FILE_SIZE            NUMBER,
   CREATED              DATE,
   USER_ID              VARCHAR2(40),
   CONSTRAINT PK_OA_SPLIT_LOG PRIMARY KEY (SPLIT_LOG_ID)
);

COMMENT ON TABLE OA_SPLIT_LOG IS
'文件拆分记录表';

COMMENT ON COLUMN OA_SPLIT_LOG.SPLIT_LOG_ID IS
'编号';

COMMENT ON COLUMN OA_SPLIT_LOG.UNIT_ID IS
'拆分单位ID';

COMMENT ON COLUMN OA_SPLIT_LOG.BUSS_ID IS
'文件拆分业务ID';

COMMENT ON COLUMN OA_SPLIT_LOG.PARENT_ID IS
'父ID';

COMMENT ON COLUMN OA_SPLIT_LOG.FILE_NAME IS
'拆分的文件名';

COMMENT ON COLUMN OA_SPLIT_LOG.FILE_PATH IS
'文件相对路径';

COMMENT ON COLUMN OA_SPLIT_LOG.FILE_SIZE IS
'文件大小(单位：字节)';

COMMENT ON COLUMN OA_SPLIT_LOG.CREATED IS
'拆分时间';

COMMENT ON COLUMN OA_SPLIT_LOG.USER_ID IS
'操作人员ID';

ALTER TABLE OA_SPLIT_LOG
   ADD CONSTRAINT FK_OA_SPLIT_REFERENCE_OA_SPLIT FOREIGN KEY (UNIT_ID)
      REFERENCES OA_SPLIT_UNIT (UNIT_ID);
