DROP TABLE OA_GWCS_ORG_CONFIG CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_GWCS_ORG_CONFIG                                    */
/*==============================================================*/
CREATE TABLE OA_GWCS_ORG_CONFIG 
(
   ID                   VARCHAR2(50)         NOT NULL,
   CONFIG_NAME          VARCHAR2(200)        NOT NULL,
   ORG_ID               VARCHAR2(2000),
   ORG_NAME             VARCHAR2(2000),
   GWCS_ORG_ID          VARCHAR2(50),
   GWCS_ORG_ADDR        VARCHAR2(50),
   GWCS_ORG_NAME        VARCHAR2(500),
   WORDTOGWCSWSDL       VARCHAR2(500),
   ARCHIVESENDWSDL      VARCHAR2(500),
   ARCHIVESERVERSENDWSDL VARCHAR2(500),
   UNIONARCHIVESENDWSDL VARCHAR2(500),
   GWCSJSPADDRESS       VARCHAR2(500),
   GWCS_ADDRESS_PATH    VARCHAR2(500),
   CONSTRAINT PK_OA_GWCS_ORG_CONFIG PRIMARY KEY (ID)
);

COMMENT ON TABLE OA_GWCS_ORG_CONFIG IS
'OA公文配置表';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.ID IS
'配置ID';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.CONFIG_NAME IS
'配置名称';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.ORG_ID IS
'OA机构地址码';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.ORG_NAME IS
'OA机构名称';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.GWCS_ORG_ID IS
'公文传输机构ID';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.GWCS_ORG_ADDR IS
'公文传输机构地址码';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.GWCS_ORG_NAME IS
'公文传输机构名称';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.WORDTOGWCSWSDL IS
'文档上次';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.ARCHIVESENDWSDL IS
'发公文传输';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.ARCHIVESERVERSENDWSDL IS
'发公文传输';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.UNIONARCHIVESENDWSDL IS
'联合发文';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.GWCSJSPADDRESS IS
'公文传输盖章地址';

COMMENT ON COLUMN OA_GWCS_ORG_CONFIG.GWCS_ADDRESS_PATH IS
'公文地址薄配置路径';

-- Add/modify columns 
alter table OA_ARCHIVE_DISPATCH add SEND_ORG_CONFIG VARCHAR2(50);
-- Add comments to the columns 
comment on column OA_ARCHIVE_DISPATCH.SEND_ORG_CONFIG
  is '公文发送单位配置ID';