-- Add/modify columns 
alter table OA_FLOW_BASEINFO add flow_tyle CHAR(1) default '1';
alter table OA_FLOW_BASEINFO add TEMPLATE_ID VARCHAR2(50);
-- Add comments to the columns 
comment on column OA_FLOW_BASEINFO.flow_tyle
  is '流程类型(1:表单 ,2: word)';
comment on column OA_FLOW_BASEINFO.TEMPLATE_ID
  is 'word模板ID';


ALTER TABLE OA_WORD_TEXTINPUT
   DROP CONSTRAINT FK_OA_WORD__REFERENCE_OA_WORD_;

DROP TABLE OA_WORD_TEMPLATE CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_WORD_TEMPLATE                                      */
/*==============================================================*/
CREATE TABLE OA_WORD_TEMPLATE 
(
   TEMPLATE_ID          VARCHAR2(50)         NOT NULL,
   TEMPLATE_NAME        VARCHAR2(500)        NOT NULL,
   TEMPLATE_CREATORTIME DATE                 DEFAULT SYSDATE NOT NULL,
   TEMPLATE_USERID      VARCHAR2(50),
   TEMPLATE_USERNAME    VARCHAR2(50),
   ORG_ID               VARCHAR2(100),
   ORG_NAME             VARCHAR2(100),
   TEMPLATE_REMARK      VARCHAR2(500),
   IS_COMMON            VARCHAR2(2)          DEFAULT 'Y' NOT NULL,
   LASTMODIFYTIME       DATE                 NOT NULL,
   TEMPLATE_SN          NUMBER,
   CONSTRAINT PK_OA_WORD_TEMPLATE PRIMARY KEY (TEMPLATE_ID)
);

COMMENT ON TABLE OA_WORD_TEMPLATE IS
'word模板表';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_ID IS
'模板主键';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_NAME IS
'模板名称';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_CREATORTIME IS
'创建时间';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_USERID IS
'创建者主键';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_USERNAME IS
'创建者';

COMMENT ON COLUMN OA_WORD_TEMPLATE.ORG_ID IS
'机构id';

COMMENT ON COLUMN OA_WORD_TEMPLATE.ORG_NAME IS
'机构名称';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_REMARK IS
'模版说明';

COMMENT ON COLUMN OA_WORD_TEMPLATE.IS_COMMON IS
'是否通用模板';

COMMENT ON COLUMN OA_WORD_TEMPLATE.LASTMODIFYTIME IS
'最后修改时间';

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_SN IS
'序号';


ALTER TABLE OA_WORD_TEXTINPUT
   DROP CONSTRAINT FK_OA_WORD__REFERENCE_OA_WORD_;

DROP TABLE OA_WORD_TEXTINPUT CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_WORD_TEXTINPUT                                     */
/*==============================================================*/
CREATE TABLE OA_WORD_TEXTINPUT 
(
   TEXTINPUT_ID         VARCHAR2(50)         NOT NULL,
   TEMPLATE_ID          VARCHAR2(50),
   TEXTINPUT_NAME       VARCHAR2(255)        NOT NULL,
   TABLE_ID             VARCHAR2(40),
   COLUMN_ID            VARCHAR2(40),
   TEXTINPUT_VALUE_TYPE VARCHAR2(2)          NOT NULL,
   TEXTINPUT_VALUE      VARCHAR2(255),
   TEXTINPUT_HELP       VARCHAR2(500),
   TEXTINPUT_FLAG       VARCHAR2(500),
   TEXTINPUT_REMARK     VARCHAR2(500),
   CONSTRAINT PK_TA_OA_WORD_TEXTINPUT1 PRIMARY KEY (TEXTINPUT_ID)
);

COMMENT ON TABLE OA_WORD_TEXTINPUT IS
'word中输入文本数据表';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_ID IS
'输入文本ID';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEMPLATE_ID IS
'模板主键';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_NAME IS
'名称';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TABLE_ID IS
'对应表名';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.COLUMN_ID IS
'对应字段名';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_VALUE_TYPE IS
'1，变量 ';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_VALUE IS
'默认值';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_HELP IS
'帮助';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_FLAG IS
'状态';

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_REMARK IS
'备注';

ALTER TABLE OA_WORD_TEXTINPUT
   ADD CONSTRAINT FK_OA_WORD__REFERENCE_OA_WORD_ FOREIGN KEY (TEMPLATE_ID)
      REFERENCES OA_WORD_TEMPLATE (TEMPLATE_ID);


DROP TABLE OA_OCTL_TEMPLATE_FILE CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_OCTL_TEMPLATE_FILE                                 */
/*==============================================================*/
CREATE TABLE OA_OCTL_TEMPLATE_FILE 
(
   TEMPLATEID           VARCHAR2(50)         NOT NULL,
   RECORDID             VARCHAR2(50)         NOT NULL,
   FILENAME             VARCHAR2(254),
   FILETYPE             VARCHAR2(50),
   FILESIZE             NUMBER(10),
   FILEDATE             DATE,
   FILEBODY             BLOB,
   FILEPATH             VARCHAR2(255),
   USERNAME             VARCHAR2(64),
   DESCRIPT             VARCHAR2(255),
   ORG_ID               VARCHAR2(50),
   RECORD_SN            NUMBER(10)
);

COMMENT ON TABLE OA_OCTL_TEMPLATE_FILE IS
'通用模板表';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.TEMPLATEID IS
'自动编号';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.RECORDID IS
'模板编号';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILENAME IS
'模板名称';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILETYPE IS
'模板类型';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILESIZE IS
'模板大小';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILEDATE IS
'模板日期';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILEBODY IS
'模板内容';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILEPATH IS
'模板所在路径';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.USERNAME IS
'用户名称';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.DESCRIPT IS
'模板描述';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.ORG_ID IS
'该模板所属的机构id';

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.RECORD_SN IS
'模板排序号';
