--代办视图，手机用。
CREATE OR REPLACE VIEW  M_V_GW_R AS
SELECT
   I.INS_ID AS LC_SLID,
   I.INS_NAME AS LC_BT,
   I.BUSITYPE_CODE AS LC_YWCODE,
   C.ACTION_NAME AS LC_HJ,
   I.Org_Id AS LC_FQJG,
   I.Accepter AS LC_FQR,
   I.Accept_Time AS LC_LCSJ,
   U.USER_ID AS LC_JSRID,
   I.Busi_Id AS LC_YWID
FROM
   OA_FLOW_BUSITYPE B,
   OA_FLOW_INSTANCE I,
   OA_FLOW_INSWFACTION C,
   OA_FLOW_ACTIONUSER R,
   TD_SM_USER U
WHERE
   I.BUSITYPE_CODE = TRIM(B.BUSITYPE_CODE)
   AND I.INS_ID = C.INS_ID
   AND I.INS_ID = R.INS_ID
   AND R.USER_NAME = U.USER_NAME
   AND C.ACTION_HANDERNAME IS NULL 
   AND I.STATUS_CODE != '04' 
   AND R.IS_HANDLE='1' 
   AND C.ACT_INSID = R.ACTIVITY;
   
--已办视图，手机用。
CREATE OR REPLACE VIEW M_V_GW_S AS
SELECT
   I.INS_ID AS LC_SLID,
   I.INS_NAME AS LC_BT,
   I.BUSITYPE_CODE AS LC_YWCODE,
   C.ACTION_NAME AS LC_HJ,
   I.Org_Id AS LC_FQJG,
   I.Accepter AS LC_FQR,
   I.Accept_Time AS LC_LCSJ,
   U.USER_ID AS LC_BLRID,
   I.Busi_Id AS LC_YWID   
FROM
   OA_FLOW_BUSITYPE B,
   OA_FLOW_INSTANCE I,
   OA_FLOW_INSWFACTION C,
   TD_SM_USER U
WHERE
   I.BUSITYPE_CODE = TRIM(B.BUSITYPE_CODE)
   AND I.INS_ID = C.INS_ID
   AND C.ACTION_HANDERNAME = U.USER_NAME
   AND C.ACTION_HANDERNAME IS not NULL 
   AND C.is_valid = 'Y';      