DROP TABLE OA_WORD_TEMPLATE_TH CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_WORD_TEMPLATE_TH                                   */
/*==============================================================*/
CREATE TABLE OA_WORD_TEMPLATE_TH 
(
   TEMPLATE_ID_TH       VARCHAR2(50)         NOT NULL,
   TEMPLATE_NAME_TH     VARCHAR2(500)        NOT NULL,
   TEMPLATE_CREATORTIME_TH DATE                 DEFAULT SYSDATE NOT NULL,
   TEMPLATE_USERID_TH   VARCHAR2(50),
   TEMPLATE_USERNAME_TH VARCHAR2(50),
   ORG_ID               VARCHAR2(100),
   ORG_NAME             VARCHAR2(100),
   TEMPLATE_REMARK_TH   VARCHAR2(500),
   IS_COMMON_TH         VARCHAR2(2)          DEFAULT 'Y' NOT NULL,
   LASTMODIFYTIME_TH    DATE                 NOT NULL,
   TEMPLATE_SN_TH       NUMBER,
   REMARK               VARCHAR2(50),
   CONSTRAINT PK_OA_WORD_TEMPLATE_TH PRIMARY KEY (TEMPLATE_ID_TH)
);

COMMENT ON TABLE OA_WORD_TEMPLATE_TH IS
'word套红模板表';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_ID_TH IS
'模板主键';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_NAME_TH IS
'模板名称';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_CREATORTIME_TH IS
'创建时间';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_USERID_TH IS
'创建者主键';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_USERNAME_TH IS
'创建者';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.ORG_ID IS
'机构id';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.ORG_NAME IS
'机构名称';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_REMARK_TH IS
'模版说明';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.IS_COMMON_TH IS
'是否套红通用模板';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.LASTMODIFYTIME_TH IS
'最后修改时间';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.TEMPLATE_SN_TH IS
'序号';

COMMENT ON COLUMN OA_WORD_TEMPLATE_TH.REMARK IS
'备用';
