DROP TABLE OA_FLOW_AGENCY CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_FLOW_AGENCY                                        */
/*==============================================================*/
CREATE TABLE OA_FLOW_AGENCY 
(
   WORK_ID              VARCHAR2(50)         DEFAULT SYSDATE,
   WORK_TYPE            VARCHAR2(50),
   WORK_NAME            VARCHAR2(100),
   START_TIME           DATE,
   END_TIME             DATE,
   AGENCY_NAME          VARCHAR2(4000),
   AGENCY_ID            VARCHAR2(4000),
   ENTRUST_NAME         VARCHAR2(4000),
   ENTRUST_ID           VARCHAR2(4000),
   FLOW_ID              VARCHAR2(100),
   AGENCY_USERNAME      VARCHAR2(4000)
);

COMMENT ON TABLE OA_FLOW_AGENCY IS
'工作委托';

COMMENT ON COLUMN OA_FLOW_AGENCY.WORK_ID IS
'主键ID';

COMMENT ON COLUMN OA_FLOW_AGENCY.WORK_TYPE IS
'工作类型';

COMMENT ON COLUMN OA_FLOW_AGENCY.WORK_NAME IS
'工作名称';

COMMENT ON COLUMN OA_FLOW_AGENCY.START_TIME IS
'开始时间';

COMMENT ON COLUMN OA_FLOW_AGENCY.END_TIME IS
'结束时间';

COMMENT ON COLUMN OA_FLOW_AGENCY.AGENCY_NAME IS
'代理人登陆名称';

COMMENT ON COLUMN OA_FLOW_AGENCY.AGENCY_ID IS
'代理人id';

COMMENT ON COLUMN OA_FLOW_AGENCY.ENTRUST_NAME IS
'委托人';

COMMENT ON COLUMN OA_FLOW_AGENCY.ENTRUST_ID IS
'委托人id';

COMMENT ON COLUMN OA_FLOW_AGENCY.FLOW_ID IS
'流程ID';

COMMENT ON COLUMN OA_FLOW_AGENCY.AGENCY_USERNAME IS
'代理人名称';


DROP TABLE OA_FLOW_AGENCY_INFO CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_FLOW_AGENCY_INFO                                   */
/*==============================================================*/
CREATE TABLE OA_FLOW_AGENCY_INFO 
(
   ID                   VARCHAR2(50)         DEFAULT SYSDATE,
   BUSITYPE_CODE        VARCHAR2(50),
   AGENCY_ID            VARCHAR2(50),
   ENTRUST_ID           VARCHAR2(50),
   INS_ID               VARCHAR2(50),
   ACTINSID             VARCHAR2(100),
   ACTION_NAME          VARCHAR2(200),
   ACTION_ID            VARCHAR2(50)
);

COMMENT ON TABLE OA_FLOW_AGENCY_INFO IS
'委托代办记录表';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.ID IS
'主键ID';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.BUSITYPE_CODE IS
'业务类型';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.AGENCY_ID IS
'代理人ID';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.ENTRUST_ID IS
'委托人ID';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.INS_ID IS
'流程实例ID';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.ACTINSID IS
'流程环节实例ID';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.ACTION_NAME IS
'环节名称';

COMMENT ON COLUMN OA_FLOW_AGENCY_INFO.ACTION_ID IS
'环节ID';
