DROP FUNCTION OA_GETORGLISTBYUSERIDS
/

CREATE OR REPLACE FUNCTION OA_GETORGLISTBYUSERIDS(SUBUSERIDS IN VARCHAR2)
RETURN VARCHAR2 AS
   RS CLOB;
         CURSOR SUBUSERIDLIST IS (SELECT COLUMN_VALUE USER_ID FROM TABLE(OA_SPLIT(SUBUSERIDS)));
         CC SUBUSERIDLIST%rowtype;
         orgids varchar2(3000);
         allorgids clob;
     begin
       open subUseridList;
       loop
         fetch subUseridList into cc;
         exit when subUseridList%NOTFOUND;
         SELECT WM_CONCAT(ORG.ORG_ID) INTO ORGIDS
          FROM TD_SM_ORGANIZATION ORG
              START WITH ORG.ORG_ID = (SELECT OU.ORG_ID FROM TD_SM_ORGUSER OU WHERE OU.USER_ID = CC.USER_ID)
          CONNECT BY PRIOR ORG.PARENT_ID = ORG.ORG_ID;
          IF ALLORGIDS IS NULL THEN
            ALLORGIDS := ORGIDS;
          ELSE
            ALLORGIDS := ALLORGIDS||','||ORGIDS;
          END IF;
       END LOOP;
      CLOSE SUBUSERIDLIST;
      SELECT WM_CONCAT(''''||ORG_ID||'''') INTO RS FROM TD_SM_ORGANIZATION O WHERE INSTR(ALLORGIDS,O.ORG_ID)>0;
       RETURN(RS);
     END;
/
