DROP view V_OA_BCODE_TABLE_MAP;

/*==============================================================*/
/* View: V_OA_BCODE_TABLE_MAP                                   */
/*==============================================================*/
CREATE OR REPLACE VIEW V_OA_BCODE_TABLE_MAP AS
SELECT T.BUSITYPE_NAME AS BUSITYPE_CODE , T.TABLE_ID AS TABLE_ID FROM  OA_FORM_BUSITYPE T
UNION ALL
SELECT TM.BUSITYPE_CODE AS BUSITYPE_CODE, TM.TABLE_ID AS TABLE_ID FROM OA_MD_TABLE_BUSINESS_MAPPING TM
WITH READ ONLY;

COMMENT ON COLUMN V_OA_BCODE_TABLE_MAP.BUSITYPE_CODE IS
'类型名称';

COMMENT ON COLUMN V_OA_BCODE_TABLE_MAP.TABLE_ID IS
'表ID';
