DROP TABLE OA_WORD_NUMBER_DEF CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_WORD_NUMBER_DEF                                    */
/*==============================================================*/
CREATE TABLE OA_WORD_NUMBER_DEF 
(
   NUMBER_TYPE        VARCHAR2(50)         NOT NULL,
   NUMBER_YEAR        VARCHAR2(50)         NOT NULL,
   NUMBER_ORDER       NUMBER,
   NUMBER_ORG_ID      CLOB,
   REMARK1            VARCHAR2(200),
   CONSTRAINT PK_OA_WORD_NUMBER_DEF PRIMARY KEY (NUMBER_TYPE, NUMBER_YEAR)
);

COMMENT ON TABLE OA_WORD_NUMBER_DEF IS
'公文编号定义表';

COMMENT ON COLUMN OA_WORD_NUMBER_DEF.NUMBER_TYPE IS
'编号类型';

COMMENT ON COLUMN OA_WORD_NUMBER_DEF.NUMBER_YEAR IS
'编号年份';

COMMENT ON COLUMN OA_WORD_NUMBER_DEF.NUMBER_ORDER IS
'排序号';

COMMENT ON COLUMN OA_WORD_NUMBER_DEF.NUMBER_ORG_ID IS
'机构号';

COMMENT ON COLUMN OA_WORD_NUMBER_DEF.REMARK1 IS
'扩展字段';
