-- Add/modify columns 
alter table OA_FLOW_WFACTIONEXT add ISDISPENSE CHAR(1);
-- Add comments to the columns 
comment on column OA_FLOW_WFACTIONEXT.ISDISPENSE
  is '是否分发';
  
DROP TABLE OA_CIRCULARIZE_FLOW CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_CIRCULARIZE_FLOW                                   */
/*==============================================================*/
CREATE TABLE OA_CIRCULARIZE_FLOW 
(
   CIRCULARIZE_ID       VARCHAR2(40)         NOT NULL,
   BUSI_ID              VARCHAR2(40)         NOT NULL,
   SEND_USERID          VARCHAR2(10),
   RECEIVE_USERID       VARCHAR2(10),
   IS_CIRCULARIZE       VARCHAR2(2),
   ENTERING_DATE        DATE,
   CIRCULARIZE_TITLE    VARCHAR2(2000),
   ACTION_FORM          VARCHAR2(200),
   INS_ID               VARCHAR2(40),
   BUSITYPE_CODE        VARCHAR2(40),
   TEMPLATE_ID          VARCHAR2(40),
   CONSTRAINT PK_OA_CIRCULARIZE_FLOW PRIMARY KEY (CIRCULARIZE_ID)
);

COMMENT ON TABLE OA_CIRCULARIZE_FLOW IS
'文件传阅表';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.CIRCULARIZE_ID IS
'主键id';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.BUSI_ID IS
'流程业务id';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.SEND_USERID IS
'发送人员id';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.RECEIVE_USERID IS
'接收人员id';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.IS_CIRCULARIZE IS
'是否已阅读';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.ENTERING_DATE IS
'录入时间';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.CIRCULARIZE_TITLE IS
'传阅标题';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.ACTION_FORM IS
'活动表单（JSP相对路径）';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.INS_ID IS
'流程实例id';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.BUSITYPE_CODE IS
'业务类型';

COMMENT ON COLUMN OA_CIRCULARIZE_FLOW.TEMPLATE_ID IS
'模板ID';
  