/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     2013-7-30 11:01:56                           */
/*==============================================================*/


DROP PROCEDURE COPYFLOWINFO
/

DROP FUNCTION OA_GETACTION_INDEX
/

DROP FUNCTION OA_GETORGLISTBYUSERIDS
/

DROP FUNCTION OA_SPLIT
/

ALTER TABLE OA_FLOW_ACTIONFROMDEFID
   DROP CONSTRAINT FK_FK_OA_FLOW_WFACTION_4
/

ALTER TABLE OA_FLOW_ACTIONTREECONFIG
   DROP CONSTRAINT FK_OA_FLOW_WFACTION_2
/

ALTER TABLE OA_FLOW_BASEINFO
   DROP CONSTRAINT FK_OA_FLOW_BUSITYPE_1
/

ALTER TABLE OA_FLOW_DEFINFO
   DROP CONSTRAINT FK_OA_FLOW_BASEINFO_1
/

ALTER TABLE OA_FLOW_INSTANCE
   DROP CONSTRAINT FK_OA_FLOW_STATUS_1
/

ALTER TABLE OA_FLOW_WFACTION
   DROP CONSTRAINT FK_OA_FLOW_DEFINFO
/

ALTER TABLE OA_FLOW_WFACTIONEXT
   DROP CONSTRAINT FK_FK_OA_FLOW_WFACTION_3
/

ALTER TABLE OA_FLOW_WFACTUSER
   DROP CONSTRAINT FK_OA_FLOW_WFACTION_1
/

ALTER TABLE OA_FORM_BUSITYPE
   DROP CONSTRAINT FK_OA_MD_TABLE_2
/

ALTER TABLE OA_WORD_TEXTINPUT
   DROP CONSTRAINT FK_OA_WORD__REFERENCE_OA_WORD_
/

ALTER TABLE OA_ACT_COL_STAUTS
   DROP CONSTRAINT FK_OA_FLOW_WFACTION_5
/

ALTER TABLE OA_ACT_TEXT_STAUTS
   DROP CONSTRAINT FK_OA_FLOW_WFACTION_6
/

ALTER TABLE OA_COL_STAUTS_CONTORL
   DROP CONSTRAINT FK_OA_FORM_BUSITYPE_2
/

ALTER TABLE OA_FORM_TAG_CONFIG
   DROP CONSTRAINT FK_OA_FORM_CONFIG
/

ALTER TABLE OA_FORM_TAG_CONFIG
   DROP CONSTRAINT FK_OA_TAG_TYPE_1
/

ALTER TABLE OA_MD_COLUMNS
   DROP CONSTRAINT FK_OA_MD_CO_REFERENCE_OA_MD_TA
/

DROP view VIEW_OA_INSTANCE
/

DROP view VIEW_OA_TOBEWORK_LIST
/

DROP view VIEW_OA_WORK_LIST
/

DROP view V_PROCESS_CONFIG
/

DROP TABLE ACTPROPERTIES CASCADE CONSTRAINTS
/

DROP TABLE OA_DOCUMENT_COMIDEA CASCADE CONSTRAINTS
/

DROP TABLE OA_DOCUMENT_FILE CASCADE CONSTRAINTS
/

DROP TABLE OA_DOCUMENT_SIGNATURE CASCADE CONSTRAINTS
/

DROP TABLE OA_FC_ATTACH CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_ACTCOUNTERSIGNUSER CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_ACTIONFROMDEFID CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_ACTIONTREECONFIG CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_ACTIONTYPE CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_ACTIONUSER CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_BASEINFO CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_BUSITYPE CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_DEFINFO CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_FORM CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_INSTANCE CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_INSVIEWLIST CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_INSWFACTION CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_STATUS CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_WFACTION CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_WFACTIONEXT CASCADE CONSTRAINTS
/

DROP TABLE OA_FLOW_WFACTUSER CASCADE CONSTRAINTS
/

DROP TABLE OA_FORM_BUSITYPE CASCADE CONSTRAINTS
/

DROP TABLE OA_OCTL_TEMPLATE_FILE CASCADE CONSTRAINTS
/

DROP TABLE OA_SIGNATURE CASCADE CONSTRAINTS
/

DROP TABLE OA_WORD_TEMPLATE CASCADE CONSTRAINTS
/

DROP TABLE OA_WORD_TEXTINPUT CASCADE CONSTRAINTS
/

DROP TABLE OA_ACT_COL_STAUTS CASCADE CONSTRAINTS
/

DROP TABLE OA_ACT_TEXT_STAUTS CASCADE CONSTRAINTS
/

DROP TABLE OA_COL_STAUTS_CONTORL CASCADE CONSTRAINTS
/

DROP TABLE OA_FORM_CONFIG CASCADE CONSTRAINTS
/

DROP TABLE OA_FORM_TAG_CONFIG CASCADE CONSTRAINTS
/

DROP TABLE OA_MD_COLUMNS CASCADE CONSTRAINTS
/

DROP TABLE OA_MD_TABLE CASCADE CONSTRAINTS
/

DROP TABLE OA_MD_TABLE_BUSINESS_MAPPING CASCADE CONSTRAINTS
/

DROP TABLE OA_ORG_AREA CASCADE CONSTRAINTS
/

DROP TABLE OA_ORG_TYPE CASCADE CONSTRAINTS
/

DROP TABLE OA_TAG_TYPE CASCADE CONSTRAINTS
/

DROP TYPE OA_TYPE_SPLIT
/

DROP SEQUENCE SEQ_ACT_COL_STATUS
/

DROP SEQUENCE SEQ_ACT_TEXT_STATUS
/

CREATE SEQUENCE SEQ_ACT_COL_STATUS
INCREMENT BY 1
START WITH 626
 MAXVALUE 99999999999999999
 NOMINVALUE
NOCYCLE
NOORDER
/

CREATE SEQUENCE SEQ_ACT_TEXT_STATUS
INCREMENT BY 1
START WITH 82
 MAXVALUE 999999999999999999
 NOMINVALUE
NOCYCLE
NOORDER
/


CREATE OR REPLACE TYPE OA_TYPE_SPLIT AS TABLE OF VARCHAR2(50)
/

/
/*==============================================================*/
/* Table: ACTPROPERTIES                                         */
/*==============================================================*/
CREATE TABLE ACTPROPERTIES 
(
   PROPERTY_NAME        VARCHAR2(50)         NOT NULL
)
/

COMMENT ON TABLE ACTPROPERTIES IS
'活动别名表'
/

/*==============================================================*/
/* Table: OA_DOCUMENT_COMIDEA                                   */
/*==============================================================*/
CREATE TABLE OA_DOCUMENT_COMIDEA 
(
   IDEA_ID               VARCHAR2(50),
   IDEA_CONTENT         VARCHAR2(500),
   USER_ID              VARCHAR2(50)
)
/

COMMENT ON TABLE OA_DOCUMENT_COMIDEA IS
'意见表'
/

COMMENT ON COLUMN OA_DOCUMENT_COMIDEA.IDEA_ID IS
' 主键'
/

COMMENT ON COLUMN OA_DOCUMENT_COMIDEA.IDEA_CONTENT IS
'意见内容'
/

COMMENT ON COLUMN OA_DOCUMENT_COMIDEA.USER_ID IS
'用户'
/

/*==============================================================*/
/* Table: OA_DOCUMENT_FILE                                      */
/*==============================================================*/
CREATE TABLE OA_DOCUMENT_FILE 
(
   FILEID               NUMBER(10)           NOT NULL,
   RECORDID             VARCHAR2(100),
   FILENAME             VARCHAR2(254),
   FILETYPE             VARCHAR2(4),
   FILESIZE             NUMBER(10),
   FILEDATE             DATE,
   FILEBODY             BLOB,
   FILEPATH             VARCHAR2(128),
   USERNAME             VARCHAR2(64),
   DESCRIPT             VARCHAR2(255)
)
/

COMMENT ON TABLE OA_DOCUMENT_FILE IS
'文档表'
/

/*==============================================================*/
/* Table: OA_DOCUMENT_SIGNATURE                                 */
/*==============================================================*/
CREATE TABLE OA_DOCUMENT_SIGNATURE 
(
   SIGNATUREID          NUMBER(10)           NOT NULL,
   RECORDID             VARCHAR2(50),
   MARKNAME             VARCHAR2(64),
   USERNAME             VARCHAR2(64),
   DATETIME             DATE,
   HOSTNAME             VARCHAR2(50),
   MARKGUID             VARCHAR2(128)
)
/

COMMENT ON TABLE OA_DOCUMENT_SIGNATURE IS
'印章签名表保存'
/

/*==============================================================*/
/* Table: OA_FC_ATTACH                                          */
/*==============================================================*/
CREATE TABLE OA_FC_ATTACH 
(
   EXTEND               CHAR(255),
   DJBH                 VARCHAR2(40)         NOT NULL,
   DJ_SN                NUMBER(10),
   FILENAME             CHAR(255),
   ATTACHID             CHAR(11)             NOT NULL,
   BZ                   VARCHAR2(255),
   DJSN                 VARCHAR2(40),
   ATTACHCONTENT        BLOB,
   FILEPOS              VARCHAR2(500),
   UPLOAD_MODE          CHAR                 DEFAULT '1',
   CC_FORM_INSTANCEID   VARCHAR2(50),
   CREATOR              VARCHAR2(100)
)
/

COMMENT ON TABLE OA_FC_ATTACH IS
'附件表'
/

COMMENT ON COLUMN OA_FC_ATTACH.UPLOAD_MODE IS
'文件存取模式：1-数据库、2-本地磁盘、3-FTP远程服务器'
/

COMMENT ON COLUMN OA_FC_ATTACH.CC_FORM_INSTANCEID IS
'业务编号'
/

COMMENT ON COLUMN OA_FC_ATTACH.CREATOR IS
'创建人'
/

/*==============================================================*/
/* Table: OA_FLOW_ACTCOUNTERSIGNUSER                            */
/*==============================================================*/
CREATE TABLE OA_FLOW_ACTCOUNTERSIGNUSER 
(
   ACTIONUSER_ID        VARCHAR2(50),
   INS_ID               VARCHAR2(50),
   ACT_DEFID            VARCHAR2(100),
   ACTIVITY             VARCHAR2(100),
   ACTIVITYPROCESSID    VARCHAR2(100),
   ACTIVITYPROCESSDEFNAME VARCHAR2(100),
   USER_NAME            VARCHAR2(100),
   IS_HANDLE            VARCHAR2(2),
   COUNTERSIGN_TYPE     VARCHAR2(50),
   COUNTERSIGN_ORDER    NUMBER,
   IS_COUNTERSIGNPERSON VARCHAR2(2)
)
/

COMMENT ON TABLE OA_FLOW_ACTCOUNTERSIGNUSER IS
'环节会签表'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.ACTIONUSER_ID IS
'任务ID'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.ACT_DEFID IS
'环节定义ID'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.ACTIVITY IS
'环节实例ID'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.ACTIVITYPROCESSID IS
'环节流程实例ID'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.ACTIVITYPROCESSDEFNAME IS
'环节流程实例定义名称'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.USER_NAME IS
'用户登陆名称'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.IS_HANDLE IS
'是否已处理'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.COUNTERSIGN_TYPE IS
'会签类型'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.COUNTERSIGN_ORDER IS
'会签顺序'
/

COMMENT ON COLUMN OA_FLOW_ACTCOUNTERSIGNUSER.IS_COUNTERSIGNPERSON IS
'是否是会签当前处理人'
/

/*==============================================================*/
/* Table: OA_FLOW_ACTIONFROMDEFID                               */
/*==============================================================*/
CREATE TABLE OA_FLOW_ACTIONFROMDEFID 
(
   FORM_ID              VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   ACTION_FORM          VARCHAR2(300),
   CONSTRAINT PK_OA_FLOW_ACTION_FROMDEFID PRIMARY KEY (FORM_ID)
)
/

COMMENT ON TABLE OA_FLOW_ACTIONFROMDEFID IS
'活动表单定义表'
/

COMMENT ON COLUMN OA_FLOW_ACTIONFROMDEFID.FORM_ID IS
'表单定义ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONFROMDEFID.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONFROMDEFID.ACTION_FORM IS
'活动表单（JSP相对路径）'
/

/*==============================================================*/
/* Table: OA_FLOW_ACTIONTREECONFIG                              */
/*==============================================================*/
CREATE TABLE OA_FLOW_ACTIONTREECONFIG 
(
   CONFIG_ID            VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   TREE_ROLE            VARCHAR2(50),
   TREE_NODETYPE        VARCHAR2(50),
   CONSTRAINT PK_OA_FLOW_ACT_TREECONFIGID PRIMARY KEY (CONFIG_ID)
)
/

COMMENT ON TABLE OA_FLOW_ACTIONTREECONFIG IS
'活动树配置表'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTREECONFIG.CONFIG_ID IS
'配置ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTREECONFIG.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTREECONFIG.TREE_ROLE IS
'树的权限'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTREECONFIG.TREE_NODETYPE IS
'树的节点类型'
/

/*==============================================================*/
/* Table: OA_FLOW_ACTIONTYPE                                    */
/*==============================================================*/
CREATE TABLE OA_FLOW_ACTIONTYPE 
(
   ACTIONTYPE_ID        VARCHAR2(50)         NOT NULL,
   ACTIONTYPE_NAME      VARCHAR2(50)         NOT NULL,
   ACTIONTYPE_CODE      VARCHAR2(50)         NOT NULL,
   CONSTRAINT PK_OA_ACTION_TYPE PRIMARY KEY (ACTIONTYPE_ID)
)
/

COMMENT ON TABLE OA_FLOW_ACTIONTYPE IS
'环节类型表'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTYPE.ACTIONTYPE_ID IS
'类型编码'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTYPE.ACTIONTYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN OA_FLOW_ACTIONTYPE.ACTIONTYPE_CODE IS
'类型描述'
/

/*==============================================================*/
/* Table: OA_FLOW_ACTIONUSER                                    */
/*==============================================================*/
CREATE TABLE OA_FLOW_ACTIONUSER 
(
   ACTIONUSER_ID        VARCHAR2(50)         NOT NULL,
   INS_ID               VARCHAR2(50),
   ACT_DEFID            VARCHAR2(100),
   ACTIVITY             VARCHAR2(100),
   ACTIVITYPROCESSID    VARCHAR2(100),
   ACTIVITYPROCESSDEFNAME VARCHAR2(100),
   USER_NAME            VARCHAR2(100),
   IS_HANDLE            VARCHAR2(2),
   COUNTERSIGN_TYPE     VARCHAR2(50),
   COUNTERSIGN_ORDER    NUMBER,
   IS_COUNTERSIGNPERSON VARCHAR2(2),
   COUNTERSIGN_GROUP    VARCHAR2(50),
   COUNTERSIGN_MAXORDER NUMBER,
   CONSTRAINT PK_OA_FLOW_ACTIONUSER PRIMARY KEY (ACTIONUSER_ID)
)
/

COMMENT ON TABLE OA_FLOW_ACTIONUSER IS
'环节任务表'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.ACTIONUSER_ID IS
'任务ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.ACT_DEFID IS
'环节定义ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.ACTIVITY IS
'环节实例ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.ACTIVITYPROCESSID IS
'环节流程实例ID'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.ACTIVITYPROCESSDEFNAME IS
'环节流程实例定义名称'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.USER_NAME IS
'用户登陆名称'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.IS_HANDLE IS
'是否已处理'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.COUNTERSIGN_TYPE IS
'会签类型'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.COUNTERSIGN_ORDER IS
'会签顺序'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.IS_COUNTERSIGNPERSON IS
'是否是会签当前处理人'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.COUNTERSIGN_GROUP IS
'会签分组'
/

COMMENT ON COLUMN OA_FLOW_ACTIONUSER.COUNTERSIGN_MAXORDER IS
'会签顺序最大值'
/

/*==============================================================*/
/* Table: OA_FLOW_BASEINFO                                      */
/*==============================================================*/
CREATE TABLE OA_FLOW_BASEINFO 
(
   FLOW_ID              VARCHAR2(50)         NOT NULL,
   BUSITYPE_CODE        VARCHAR2(50),
   BUSINESS_ID          VARCHAR2(50),
   FLOW_NAME            VARCHAR2(200)        NOT NULL,
   ORG_ID               VARCHAR2(50),
   IS_INDIVI            CHAR(1)              NOT NULL,
   IS_VALID             CHAR(1)              NOT NULL,
   FLOW_LIMIT           NUMBER,
   LIMIT_UNIT           CHAR(1),
   CREATE_TIME          DATE                 DEFAULT SYSDATE NOT NULL,
   FROM_PATH            VARCHAR2(200)        NOT NULL,
   IS_TEXT              CHAR(1)              DEFAULT '1',
   INSNAME_RULE         VARCHAR2(200),
   FLOW_TYLE            CHAR(1)              DEFAULT '1',
   TEMPLATE_ID          VARCHAR2(50),
   CONSTRAINT PK_OA_FLOW_FLOWBASEINFO PRIMARY KEY (FLOW_ID)
)
/

COMMENT ON TABLE OA_FLOW_BASEINFO IS
'流程基本信息表'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.FLOW_ID IS
'流程ID'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.BUSINESS_ID IS
'业务ID'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.FLOW_NAME IS
'流程名称'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.ORG_ID IS
'机构ID'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.IS_INDIVI IS
'是否个性化流程'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.IS_VALID IS
'是否有效'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.FLOW_LIMIT IS
'流程期限'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.LIMIT_UNIT IS
'期限单位'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.CREATE_TIME IS
'创建时间'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.FROM_PATH IS
'表单路径'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.IS_TEXT IS
'是否有正文'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.FLOW_TYLE IS
'流程类型(1:表单 ,2: word)'
/

COMMENT ON COLUMN OA_FLOW_BASEINFO.TEMPLATE_ID IS
'word模板ID'
/

/*==============================================================*/
/* Table: OA_FLOW_BUSITYPE                                      */
/*==============================================================*/
CREATE TABLE OA_FLOW_BUSITYPE 
(
   BUSITYPE_CODE        VARCHAR2(50)         NOT NULL,
   BUSITYPE_NAME        VARCHAR2(50)         NOT NULL,
   TYPE_DESC            VARCHAR2(200),
   IS_VALID             CHAR(1)              DEFAULT 'Y' NOT NULL,
   CONSTRAINT PK_OA_BUSI_TYPE PRIMARY KEY (BUSITYPE_CODE)
)
/

COMMENT ON TABLE OA_FLOW_BUSITYPE IS
'业务类型表'
/

COMMENT ON COLUMN OA_FLOW_BUSITYPE.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN OA_FLOW_BUSITYPE.BUSITYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN OA_FLOW_BUSITYPE.TYPE_DESC IS
'类型描述'
/

COMMENT ON COLUMN OA_FLOW_BUSITYPE.IS_VALID IS
'是否有效'
/

/*==============================================================*/
/* Table: OA_FLOW_DEFINFO                                       */
/*==============================================================*/
CREATE TABLE OA_FLOW_DEFINFO 
(
   FLOW_DEFID           VARCHAR2(50)         NOT NULL,
   DEF_ID               VARCHAR2(50)         NOT NULL,
   FLOW_ID              VARCHAR2(50)         NOT NULL,
   FLOW_VERSION         VARCHAR2(5),
   PACKAGE_ID           VARCHAR2(50),
   IS_VALID             CHAR(1)              DEFAULT 'Y' NOT NULL,
   CREATE_TIME          DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_OA_FLOW_FLOWDEFINFO PRIMARY KEY (DEF_ID)
)
/

COMMENT ON TABLE OA_FLOW_DEFINFO IS
'流程定义表'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.FLOW_DEFID IS
'流程定义ID'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.DEF_ID IS
'流程定义主键'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.FLOW_ID IS
'流程ID'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.FLOW_VERSION IS
'流程版本'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.PACKAGE_ID IS
'流程包'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.IS_VALID IS
'是否有效'
/

COMMENT ON COLUMN OA_FLOW_DEFINFO.CREATE_TIME IS
'创建时间'
/

/*==============================================================*/
/* Table: OA_FLOW_FORM                                          */
/*==============================================================*/
CREATE TABLE OA_FLOW_FORM 
(
   FORM_PATH            VARCHAR2(200),
   FORM_NAME            VARCHAR2(100),
   FORM_DESC            VARCHAR2(500),
   CREATOR_TIME         DATE                 DEFAULT SYSDATE
)
/

COMMENT ON TABLE OA_FLOW_FORM IS
'流程表单表'
/

COMMENT ON COLUMN OA_FLOW_FORM.FORM_PATH IS
'表单路径'
/

COMMENT ON COLUMN OA_FLOW_FORM.FORM_NAME IS
'表单名称'
/

COMMENT ON COLUMN OA_FLOW_FORM.FORM_DESC IS
'表单描述'
/

COMMENT ON COLUMN OA_FLOW_FORM.CREATOR_TIME IS
'创建时间'
/

/*==============================================================*/
/* Table: OA_FLOW_INSTANCE                                      */
/*==============================================================*/
CREATE TABLE OA_FLOW_INSTANCE 
(
   INS_ID               VARCHAR2(50)         NOT NULL,
   STATUS_CODE          VARCHAR2(50),
   BUSITYPE_CODE        VARCHAR2(50),
   INS_NAME             VARCHAR2(200)        NOT NULL,
   INS_CODE             VARCHAR2(50)         NOT NULL,
   ACCEPT_TIME          DATE                 NOT NULL,
   ACCEPTER             VARCHAR2(50),
   ACCEPTER_ID          VARCHAR2(50)         NOT NULL,
   DEF_ID               VARCHAR2(50)         NOT NULL,
   ORG_ID               VARCHAR2(100)        NOT NULL,
   FLOW_ID              VARCHAR2(50),
   LASTMODIFEDTIME      DATE                 DEFAULT SYSDATE,
   IS_VALID             CHAR(1)              DEFAULT 'Y',
   REMARK1              VARCHAR2(50),
   REMARK2              VARCHAR2(50),
   CC_FORM_INSTANCEID   VARCHAR2(50)         NOT NULL,
   BUSI_ID              VARCHAR2(50)         NOT NULL,
   CONSTRAINT PK_OA_INS_INSTANCE PRIMARY KEY (INS_ID)
)
/

COMMENT ON TABLE OA_FLOW_INSTANCE IS
'流程实例表'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.STATUS_CODE IS
'类型编码'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.INS_NAME IS
'实例名称'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.INS_CODE IS
'实例编号'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.ACCEPT_TIME IS
'受理时间'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.ACCEPTER IS
'受理人'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.ACCEPTER_ID IS
'受理人ID'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.DEF_ID IS
'流程定义ID'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.ORG_ID IS
'机构ID'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.FLOW_ID IS
'流程ID'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.LASTMODIFEDTIME IS
'最后修改时间'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.IS_VALID IS
'是否有效'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.REMARK1 IS
'备注1'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.REMARK2 IS
'备注2'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.CC_FORM_INSTANCEID IS
'平台实例ID'
/

COMMENT ON COLUMN OA_FLOW_INSTANCE.BUSI_ID IS
'业务实例ID'
/

/*==============================================================*/
/* Table: OA_FLOW_INSVIEWLIST                                   */
/*==============================================================*/
CREATE TABLE OA_FLOW_INSVIEWLIST 
(
   VIEWLIST_ID          VARCHAR2(50)         NOT NULL,
   INS_ID               VARCHAR2(50),
   ACTION_ID            VARCHAR2(50)         NOT NULL,
   ACTION_NAME          VARCHAR2(100)        NOT NULL,
   ACTION_HANDERIDEA    VARCHAR2(1000)       NOT NULL,
   HANDER_TIME          DATE                 NOT NULL,
   IS_VALID             CHAR(1)              DEFAULT 'Y',
   REMARK1              VARCHAR2(50),
   REMARK2              VARCHAR2(50),
   ORG_ID               VARCHAR2(100),
   ORG_NAME             VARCHAR2(100),
   USER_ID              VARCHAR2(100),
   USER_NAME            VARCHAR2(100),
   TABLE_NAME           VARCHAR2(100),
   COLUMN_NAME          VARCHAR2(100),
   CONSTRAINT PK_OA_INS_VIEWLIST PRIMARY KEY (VIEWLIST_ID)
)
/

COMMENT ON TABLE OA_FLOW_INSVIEWLIST IS
'意见列表'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.VIEWLIST_ID IS
'意见ID'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.ACTION_NAME IS
'活动名称'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.ACTION_HANDERIDEA IS
'活动处理意见'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.HANDER_TIME IS
'填入意见时间'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.IS_VALID IS
'是否有效'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.REMARK1 IS
'备注1'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.REMARK2 IS
'备注2'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.ORG_ID IS
'机构ID'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.ORG_NAME IS
'机构名称'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.USER_ID IS
'用户ID'
/

COMMENT ON COLUMN OA_FLOW_INSVIEWLIST.USER_NAME IS
'用户名称'
/

/*==============================================================*/
/* Table: OA_FLOW_INSWFACTION                                   */
/*==============================================================*/
CREATE TABLE OA_FLOW_INSWFACTION 
(
   FLOW_ACTION_ID       VARCHAR2(50)         NOT NULL,
   INS_ID               VARCHAR2(50),
   ACTION_ID            VARCHAR2(50)         NOT NULL,
   ACTION_NAME          VARCHAR2(100),
   ACTION_HANDERID      VARCHAR2(50),
   ACTION_HANDERNAME    VARCHAR2(100),
   TACHE_BEGIN_TIME     DATE                 NOT NULL,
   TACHE_END_TIME       DATE,
   TACHE_LIMIT          NUMBER,
   LIMIT_TYPE           CHAR(1),
   SPEND_LIMIT          NUMBER,
   IS_OVERDUE           CHAR(1),
   IS_VALID             CHAR(1)              DEFAULT 'Y',
   REMARK1              VARCHAR2(50),
   REMARK2              VARCHAR2(50),
   ACT_INSID            VARCHAR2(100),
   ACT_DEFID            VARCHAR2(100),
   PROCESSID            VARCHAR2(100),
   STATE                VARCHAR2(50),
   ACTION_FORM          VARCHAR2(100),
   CONSTRAINT PK_OA_INS_WFACTION PRIMARY KEY (FLOW_ACTION_ID)
)
/

COMMENT ON TABLE OA_FLOW_INSWFACTION IS
'流程活动业务表'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.FLOW_ACTION_ID IS
'流程活动ID'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACTION_NAME IS
'活动名称'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACTION_HANDERID IS
'活动处理人ID'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACTION_HANDERNAME IS
'活动处理人'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.TACHE_BEGIN_TIME IS
'活动开始时间'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.TACHE_END_TIME IS
'活动结束时间'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.TACHE_LIMIT IS
'活动时限'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.LIMIT_TYPE IS
'时限单位'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.SPEND_LIMIT IS
'所用时长'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.IS_OVERDUE IS
'是否超期'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.IS_VALID IS
'是否有效'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.REMARK1 IS
'备注1'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.REMARK2 IS
'备注2'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACT_INSID IS
'环节实例ID'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACT_DEFID IS
'环节定义ID'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.PROCESSID IS
'流程实例id'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.STATE IS
'状态'
/

COMMENT ON COLUMN OA_FLOW_INSWFACTION.ACTION_FORM IS
'处理页面'
/

/*==============================================================*/
/* Table: OA_FLOW_STATUS                                        */
/*==============================================================*/
CREATE TABLE OA_FLOW_STATUS 
(
   STATUS_CODE          VARCHAR2(50)         NOT NULL,
   STATUS_NAME          VARCHAR2(50)         NOT NULL,
   CONSTRAINT PK_OA_FLOW_STATUS PRIMARY KEY (STATUS_CODE)
)
/

COMMENT ON TABLE OA_FLOW_STATUS IS
'流程状态表'
/

COMMENT ON COLUMN OA_FLOW_STATUS.STATUS_CODE IS
'类型编码'
/

COMMENT ON COLUMN OA_FLOW_STATUS.STATUS_NAME IS
'类型名称'
/

/*==============================================================*/
/* Table: OA_FLOW_WFACTION                                      */
/*==============================================================*/
CREATE TABLE OA_FLOW_WFACTION 
(
   ACTION_ID            VARCHAR2(50)         NOT NULL,
   DEF_ID               VARCHAR2(50),
   ACTION_DEFID         VARCHAR2(50),
   ACTION_NAME          VARCHAR2(100)        NOT NULL,
   ACTION_ALIAS         VARCHAR2(100),
   ACTION_LIMIT         NUMBER,
   LIMIT_UNIT           CHAR(1)              DEFAULT 'D',
   ACTIONTYPE_CODE      VARCHAR2(50),
   REMARK               VARCHAR2(200),
   CREATE_TIME          DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_OA_FLOW_WFACTION PRIMARY KEY (ACTION_ID)
)
/

COMMENT ON TABLE OA_FLOW_WFACTION IS
'流程活动定义表'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.DEF_ID IS
'流程定义主键'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.ACTION_DEFID IS
'活动定义id'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.ACTION_NAME IS
'活动名称'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.ACTION_ALIAS IS
'活动别名'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.ACTION_LIMIT IS
'活动时限'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.LIMIT_UNIT IS
'时限单位'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.ACTIONTYPE_CODE IS
'活动类型编号'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.REMARK IS
'备注'
/

COMMENT ON COLUMN OA_FLOW_WFACTION.CREATE_TIME IS
'创建时间'
/

/*==============================================================*/
/* Table: OA_FLOW_WFACTIONEXT                                   */
/*==============================================================*/
CREATE TABLE OA_FLOW_WFACTIONEXT 
(
   ACTIONEXT_ID         VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   ISSHOWUSER           CHAR(1),
   ISSHOWREJECT         CHAR(1),
   CREATE_TIME          DATE                 DEFAULT SYSDATE,
   ISSHOWBACK           CHAR(1)              DEFAULT 'N',
   AUTOASSIGNMENT       VARCHAR2(100),
   ISSIGNJOINBYORDER    VARCHAR2(100),
   CONSTRAINT PK_OA_FLOW_WFACTION_EXT PRIMARY KEY (ACTIONEXT_ID)
)
/

COMMENT ON TABLE OA_FLOW_WFACTIONEXT IS
'活动扩展表'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.ACTIONEXT_ID IS
'活动扩展id'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.ISSHOWUSER IS
'是否动态选择执行人'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.ISSHOWREJECT IS
'是否退窗'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.CREATE_TIME IS
'创建时间'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.ISSHOWBACK IS
'是否回退'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.AUTOASSIGNMENT IS
'前置活动执行人'
/

COMMENT ON COLUMN OA_FLOW_WFACTIONEXT.ISSIGNJOINBYORDER IS
'是否按顺序会签'
/

/*==============================================================*/
/* Table: OA_FLOW_WFACTUSER                                     */
/*==============================================================*/
CREATE TABLE OA_FLOW_WFACTUSER 
(
   WFACTUSER_ID         VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   USER_ID              VARCHAR2(50)         NOT NULL,
   USER_NAME            VARCHAR2(100)        NOT NULL,
   ACTUSER_TYPE         CHAR(1)              DEFAULT '1' NOT NULL,
   CREATE_TIME          DATE                 DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_OA_FLOW_WFACTUSER PRIMARY KEY (WFACTUSER_ID)
)
/

COMMENT ON TABLE OA_FLOW_WFACTUSER IS
'流程活动用户表'
/

COMMENT ON COLUMN OA_FLOW_WFACTUSER.WFACTUSER_ID IS
'主键'
/

COMMENT ON COLUMN OA_FLOW_WFACTUSER.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_FLOW_WFACTUSER.USER_ID IS
'用户ID'
/

COMMENT ON COLUMN OA_FLOW_WFACTUSER.USER_NAME IS
'用户名称 '
/

COMMENT ON COLUMN OA_FLOW_WFACTUSER.ACTUSER_TYPE IS
'环节用户类型'
/

COMMENT ON COLUMN OA_FLOW_WFACTUSER.CREATE_TIME IS
'创建时间表'
/

/*==============================================================*/
/* Table: OA_FORM_BUSITYPE                                      */
/*==============================================================*/
CREATE TABLE OA_FORM_BUSITYPE 
(
   BUSITYPE_CODE        VARCHAR2(50)         NOT NULL,
   BUSITYPE_NAME        VARCHAR2(50)         NOT NULL,
   TYPE_DESC            VARCHAR2(200),
   IS_VALID             CHAR(1)              DEFAULT 'Y' NOT NULL,
   TABLE_ID             VARCHAR2(50),
   CONSTRAINT PK_OA_FORM_BUSITYPE PRIMARY KEY (BUSITYPE_CODE)
)
/

COMMENT ON TABLE OA_FORM_BUSITYPE IS
'表单业务类型表'
/

COMMENT ON COLUMN OA_FORM_BUSITYPE.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN OA_FORM_BUSITYPE.BUSITYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN OA_FORM_BUSITYPE.TYPE_DESC IS
'类型描述'
/

COMMENT ON COLUMN OA_FORM_BUSITYPE.IS_VALID IS
'是否有效'
/

COMMENT ON COLUMN OA_FORM_BUSITYPE.TABLE_ID IS
'表ID'
/

/*==============================================================*/
/* Table: OA_OCTL_TEMPLATE_FILE                                 */
/*==============================================================*/
CREATE TABLE OA_OCTL_TEMPLATE_FILE 
(
   TEMPLATEID           VARCHAR2(50)         NOT NULL,
   RECORDID             VARCHAR2(50)         NOT NULL,
   FILENAME             VARCHAR2(254),
   FILETYPE             VARCHAR2(50),
   FILESIZE             NUMBER(10),
   FILEDATE             DATE,
   FILEBODY             BLOB,
   FILEPATH             VARCHAR2(255),
   USERNAME             VARCHAR2(64),
   DESCRIPT             VARCHAR2(255),
   ORG_ID               VARCHAR2(50),
   RECORD_SN            NUMBER(10)
)
/

COMMENT ON TABLE OA_OCTL_TEMPLATE_FILE IS
'通用模板表'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.TEMPLATEID IS
'自动编号'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.RECORDID IS
'模板编号'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILENAME IS
'模板名称'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILETYPE IS
'模板类型'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILESIZE IS
'模板大小'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILEDATE IS
'模板日期'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILEBODY IS
'模板内容'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.FILEPATH IS
'模板所在路径'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.USERNAME IS
'用户名称'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.DESCRIPT IS
'模板描述'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.ORG_ID IS
'该模板所属的机构id'
/

COMMENT ON COLUMN OA_OCTL_TEMPLATE_FILE.RECORD_SN IS
'模板排序号'
/

/*==============================================================*/
/* Table: OA_SIGNATURE                                          */
/*==============================================================*/
CREATE TABLE OA_SIGNATURE 
(
   SIGNATUREID          NUMBER(10)           NOT NULL,
   USERNAME             VARCHAR2(64),
   PASSWORD             VARCHAR2(64),
   MARKNAME             VARCHAR2(254),
   MARKTYPE             VARCHAR2(50),
   MARKBODY             BLOB,
   MARKPATH             VARCHAR2(128),
   MARKSIZE             NUMBER(10),
   MARKDATE             DATE
)
/

COMMENT ON TABLE OA_SIGNATURE IS
'印章表'
/

/*==============================================================*/
/* Table: OA_WORD_TEMPLATE                                      */
/*==============================================================*/
CREATE TABLE OA_WORD_TEMPLATE 
(
   TEMPLATE_ID          VARCHAR2(50)         NOT NULL,
   TEMPLATE_NAME        VARCHAR2(500)        NOT NULL,
   TEMPLATE_CREATORTIME DATE                 DEFAULT SYSDATE NOT NULL,
   TEMPLATE_USERID      VARCHAR2(50),
   TEMPLATE_USERNAME    VARCHAR2(50),
   ORG_ID               VARCHAR2(100),
   ORG_NAME             VARCHAR2(100),
   TEMPLATE_REMARK      VARCHAR2(500),
   IS_COMMON            VARCHAR2(2)          DEFAULT 'Y' NOT NULL,
   LASTMODIFYTIME       DATE                 NOT NULL,
   TEMPLATE_SN          NUMBER,
   CONSTRAINT PK_OA_WORD_TEMPLATE PRIMARY KEY (TEMPLATE_ID)
)
/

COMMENT ON TABLE OA_WORD_TEMPLATE IS
'word模板表'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_ID IS
'模板主键'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_NAME IS
'模板名称'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_CREATORTIME IS
'创建时间'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_USERID IS
'创建者主键'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_USERNAME IS
'创建者'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.ORG_ID IS
'机构id'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.ORG_NAME IS
'机构名称'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_REMARK IS
'模版说明'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.IS_COMMON IS
'是否通用模板'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.LASTMODIFYTIME IS
'最后修改时间'
/

COMMENT ON COLUMN OA_WORD_TEMPLATE.TEMPLATE_SN IS
'序号'
/

/*==============================================================*/
/* Table: OA_WORD_TEXTINPUT                                     */
/*==============================================================*/
CREATE TABLE OA_WORD_TEXTINPUT 
(
   TEXTINPUT_ID         VARCHAR2(50)         NOT NULL,
   TEMPLATE_ID          VARCHAR2(50),
   TEXTINPUT_NAME       VARCHAR2(255)        NOT NULL,
   TABLE_ID             VARCHAR2(40),
   COLUMN_ID            VARCHAR2(40),
   TEXTINPUT_VALUE_TYPE VARCHAR2(2)          NOT NULL,
   TEXTINPUT_VALUE      VARCHAR2(255),
   TEXTINPUT_HELP       VARCHAR2(500),
   TEXTINPUT_FLAG       VARCHAR2(500),
   TEXTINPUT_REMARK     VARCHAR2(500),
   CONSTRAINT PK_TA_OA_WORD_TEXTINPUT PRIMARY KEY (TEXTINPUT_ID)
)
/

COMMENT ON TABLE OA_WORD_TEXTINPUT IS
'word中输入文本数据表'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_ID IS
'输入文本ID'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEMPLATE_ID IS
'模板主键'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_NAME IS
'名称'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TABLE_ID IS
'对应表名'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.COLUMN_ID IS
'对应字段名'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_VALUE_TYPE IS
'1，变量 '
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_VALUE IS
'默认值'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_HELP IS
'帮助'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_FLAG IS
'状态'
/

COMMENT ON COLUMN OA_WORD_TEXTINPUT.TEXTINPUT_REMARK IS
'备注'
/

/*==============================================================*/
/* Table: OA_ACT_COL_STAUTS                                     */
/*==============================================================*/
CREATE TABLE OA_ACT_COL_STAUTS 
(
   ID                   VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   TABLE_ID             VARCHAR2(50)         NOT NULL,
   TABLE_CODE           VARCHAR2(50)         NOT NULL,
   COLUMN_ID            VARCHAR2(50)         NOT NULL,
   COLUMN_CODE          VARCHAR2(50)         NOT NULL,
   READONLY             CHAR(1)              DEFAULT '0' NOT NULL,
   HIDDEN               CHAR(1)              DEFAULT '0' NOT NULL,
   DISABLE              CHAR(1)              DEFAULT '0' NOT NULL,
   REQUIRED             CHAR(1),
   CONSTRAINT PK_OA_ACT_COL_STAUTS PRIMARY KEY (ID)
)
/

COMMENT ON TABLE OA_ACT_COL_STAUTS IS
'流程活动表单元素状态表(环节字段状态表)'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.ID IS
'状态id'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.TABLE_ID IS
'库表id'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.TABLE_CODE IS
'库表名称'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.COLUMN_ID IS
'字段id'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.COLUMN_CODE IS
'字段名称'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.READONLY IS
'是否只读'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.HIDDEN IS
'是否隐藏'
/

COMMENT ON COLUMN OA_ACT_COL_STAUTS.DISABLE IS
'是否禁用'
/

/*==============================================================*/
/* Table: OA_ACT_TEXT_STAUTS                                    */
/*==============================================================*/
CREATE TABLE OA_ACT_TEXT_STAUTS 
(
   ID                   VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   IS_TRACE             CHAR(1)              DEFAULT '0' NOT NULL,
   IS_RED               CHAR(1)              DEFAULT '0' NOT NULL,
   IS_READONLY          CHAR(1)              DEFAULT '0' NOT NULL,
   EXTEND_ATTRIBUTE     VARCHAR2(400),
   EXTEND_METHODS       VARCHAR2(400),
   CONSTRAINT PK_OA_ACT_TEXT_STAUTS PRIMARY KEY (ID)
)
/

COMMENT ON TABLE OA_ACT_TEXT_STAUTS IS
'流程活动表正文状态控制表(环节字段状态表)'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.ID IS
'状态id'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.ACTION_ID IS
'活动ID'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.IS_TRACE IS
'是否显示i痕迹'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.IS_RED IS
'是否可套红'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.IS_READONLY IS
'是否可编辑'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.EXTEND_ATTRIBUTE IS
'扩展属性字段扩展属性字段（直接编写属性，如ShowToolBar=1 多个属性用#分割）'
/

COMMENT ON COLUMN OA_ACT_TEXT_STAUTS.EXTEND_METHODS IS
'扩展方法字段扩展方法字段（直接编写方法，如GetMsgByName("TEMPLATE") 多个方法用#分割）'
/

/*==============================================================*/
/* Table: OA_COL_STAUTS_CONTORL                                 */
/*==============================================================*/
CREATE TABLE OA_COL_STAUTS_CONTORL 
(
   ID                   VARCHAR2(50)         NOT NULL,
   BUSITYPE_CODE        VARCHAR2(50),
   ACTION_CODE          VARCHAR2(50),
   TABLE_ID             VARCHAR2(50),
   TABLE_CODE           VARCHAR2(50)         NOT NULL,
   COLUMN_ID            VARCHAR2(50)         NOT NULL,
   COLUMN_CODE          VARCHAR2(50)         NOT NULL,
   READONLY             CHAR(1)              DEFAULT '0' NOT NULL,
   HIDDEN               CHAR(1)              DEFAULT '0' NOT NULL,
   DISABLE              CHAR(1)              DEFAULT '0' NOT NULL,
   REQUIRED             CHAR(1),
   REMARK1              VARCHAR2(500),
   CONSTRAINT PK_OA_COL_STAUTS_CONTORL PRIMARY KEY (ID)
)
/

COMMENT ON TABLE OA_COL_STAUTS_CONTORL IS
'表单元素状态表(环节字段状态表)'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.ID IS
'状态id'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.BUSITYPE_CODE IS
'表单业务类型'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.ACTION_CODE IS
'活动ID'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.TABLE_ID IS
'表ID'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.TABLE_CODE IS
'库表名称'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.COLUMN_ID IS
'字段id'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.COLUMN_CODE IS
'字段名称'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.READONLY IS
'是否只读'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.HIDDEN IS
'是否隐藏'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.DISABLE IS
'是否禁用'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.REQUIRED IS
'是否必填'
/

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.REMARK1 IS
'扩展字段'
/

/*==============================================================*/
/* Table: OA_FORM_CONFIG                                        */
/*==============================================================*/
CREATE TABLE OA_FORM_CONFIG 
(
   FORM_ID              VARCHAR2(40)         NOT NULL,
   FORM_NAME            VARCHAR2(400)        NOT NULL,
   FORM_JSP_NAME        VARCHAR2(200)        NOT NULL,
   FORM_BACKGROUND      VARCHAR2(40),
   TAG_BACKGROUND       VARCHAR2(40),
   TAG_WIDTH            VARCHAR2(40),
   TAG_HEIGHT           VARCHAR2(40),
   TAG_MARGINS          VARCHAR2(40),
   FROM_EXT_PARM        VARCHAR2(400),
   TAG_CONFIG_HTML      CLOB,
   FORM_WIDTH           VARCHAR2(40),
   IS_TEXT              VARCHAR2(2),
   CONSTRAINT PK_OA_FORM_CONFIG PRIMARY KEY (FORM_ID)
)
/

COMMENT ON TABLE OA_FORM_CONFIG IS
'表单配置表'
/

COMMENT ON COLUMN OA_FORM_CONFIG.FORM_ID IS
'表单ID'
/

COMMENT ON COLUMN OA_FORM_CONFIG.FORM_NAME IS
'表单名称'
/

COMMENT ON COLUMN OA_FORM_CONFIG.FORM_JSP_NAME IS
'表单JSP名称'
/

COMMENT ON COLUMN OA_FORM_CONFIG.FORM_BACKGROUND IS
'表单底色'
/

COMMENT ON COLUMN OA_FORM_CONFIG.TAG_BACKGROUND IS
'元素底色'
/

COMMENT ON COLUMN OA_FORM_CONFIG.TAG_WIDTH IS
'元素宽度'
/

COMMENT ON COLUMN OA_FORM_CONFIG.TAG_HEIGHT IS
'元素高度'
/

COMMENT ON COLUMN OA_FORM_CONFIG.TAG_MARGINS IS
'元素间隔PX'
/

COMMENT ON COLUMN OA_FORM_CONFIG.FROM_EXT_PARM IS
'表单扩展属性'
/

COMMENT ON COLUMN OA_FORM_CONFIG.TAG_CONFIG_HTML IS
'配置HTML'
/

COMMENT ON COLUMN OA_FORM_CONFIG.FORM_WIDTH IS
'表单宽度'
/

COMMENT ON COLUMN OA_FORM_CONFIG.IS_TEXT IS
'是否有正文'
/

/*==============================================================*/
/* Table: OA_FORM_TAG_CONFIG                                    */
/*==============================================================*/
CREATE TABLE OA_FORM_TAG_CONFIG 
(
   TAG_ID               VARCHAR2(40)         NOT NULL,
   FORM_ID              VARCHAR2(40)         NOT NULL,
   TAG_TYPE_ID          VARCHAR2(40)         NOT NULL,
   TITLE                VARCHAR2(40),
   TABLE_ID             VARCHAR2(40),
   COLUMN_ID            VARCHAR2(40),
   STYLE_TEXT           VARCHAR2(400),
   DISPLAY_HTML         VARCHAR2(4000),
   TAG_HTML             VARCHAR2(4000),
   SELECT_TYPE          VARCHAR2(1),
   SELECT_TEXT          VARCHAR2(400),
   DEFAULT_VALUE        VARCHAR2(400),
   CONSTRAINT PK_OA_FORM_TAG_CONFIG PRIMARY KEY (TAG_ID)
)
/

COMMENT ON TABLE OA_FORM_TAG_CONFIG IS
'表单元素配置表'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.TAG_ID IS
'控件ID'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.FORM_ID IS
'表单ID'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.TAG_TYPE_ID IS
'控件类型ID'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.TITLE IS
'控件标题'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.TABLE_ID IS
'对应表名'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.COLUMN_ID IS
'对应字段名'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.STYLE_TEXT IS
'样式文本'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.DISPLAY_HTML IS
'显示HTML'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.TAG_HTML IS
'标签HTML'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.SELECT_TYPE IS
'下拉框类型'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.SELECT_TEXT IS
'下拉框文本'
/

COMMENT ON COLUMN OA_FORM_TAG_CONFIG.DEFAULT_VALUE IS
'默认值'
/

/*==============================================================*/
/* Table: OA_MD_COLUMNS                                         */
/*==============================================================*/
CREATE TABLE OA_MD_COLUMNS 
(
   COLUMN_ID            VARCHAR2(50)         NOT NULL,
   TABLE_ID             VARCHAR2(50)         NOT NULL,
   COLUMN_CODE          VARCHAR2(50)         NOT NULL,
   COLUMN_NAME          VARCHAR2(200),
   COLUMN_SN            NUMBER,
   ISVIEW               CHAR,
   CONSTRAINT PK_OA_MD_COLUMNS PRIMARY KEY (COLUMN_ID)
)
/

COMMENT ON TABLE OA_MD_COLUMNS IS
'数据元字段'
/

COMMENT ON COLUMN OA_MD_COLUMNS.COLUMN_ID IS
'字段id'
/

COMMENT ON COLUMN OA_MD_COLUMNS.TABLE_ID IS
'表id'
/

COMMENT ON COLUMN OA_MD_COLUMNS.COLUMN_CODE IS
'字段代码'
/

COMMENT ON COLUMN OA_MD_COLUMNS.COLUMN_NAME IS
'字段名称'
/

COMMENT ON COLUMN OA_MD_COLUMNS.COLUMN_SN IS
'排序号'
/

/*==============================================================*/
/* Table: OA_MD_TABLE                                           */
/*==============================================================*/
CREATE TABLE OA_MD_TABLE 
(
   TABLE_ID             VARCHAR2(50)         NOT NULL,
   TABLE_CODE           VARCHAR2(50)         NOT NULL,
   TABLE_NAME           VARCHAR2(200),
   TABLE_PK             VARCHAR2(50)         NOT NULL,
   PARENT_TABLE_ID      VARCHAR2(50),
   TABLE_SN             NUMBER,
   CONSTRAINT PK_OA_MD_TABLE PRIMARY KEY (TABLE_ID)
)
/

COMMENT ON TABLE OA_MD_TABLE IS
'数据元表名'
/

COMMENT ON COLUMN OA_MD_TABLE.TABLE_ID IS
'表id'
/

COMMENT ON COLUMN OA_MD_TABLE.TABLE_CODE IS
'表代码名称'
/

COMMENT ON COLUMN OA_MD_TABLE.TABLE_NAME IS
'表中文名称'
/

COMMENT ON COLUMN OA_MD_TABLE.TABLE_PK IS
'表主键名称'
/

COMMENT ON COLUMN OA_MD_TABLE.PARENT_TABLE_ID IS
'父表id'
/

COMMENT ON COLUMN OA_MD_TABLE.TABLE_SN IS
'排序号'
/

/*==============================================================*/
/* Table: OA_MD_TABLE_BUSINESS_MAPPING                          */
/*==============================================================*/
CREATE TABLE OA_MD_TABLE_BUSINESS_MAPPING 
(
   MAP_ID               VARCHAR2(50)         NOT NULL,
   TABLE_ID             VARCHAR2(50)         NOT NULL,
   BUSITYPE_CODE        VARCHAR2(50)         NOT NULL,
   CONSTRAINT PK_OA_MD_TABLE_BUSINESS_MAPP PRIMARY KEY (MAP_ID)
)
/

COMMENT ON TABLE OA_MD_TABLE_BUSINESS_MAPPING IS
'业务数据元关系表'
/

COMMENT ON COLUMN OA_MD_TABLE_BUSINESS_MAPPING.TABLE_ID IS
'表id'
/

COMMENT ON COLUMN OA_MD_TABLE_BUSINESS_MAPPING.BUSITYPE_CODE IS
'业务类型'
/

/*==============================================================*/
/* Table: OA_ORG_AREA                                           */
/*==============================================================*/
CREATE TABLE OA_ORG_AREA 
(
   AREA_ID              VARCHAR2(50),
   AREA_CODE            VARCHAR2(10)         NOT NULL,
   AREA_NAME            VARCHAR2(50),
   PARENT_AREA_CODE     VARCHAR2(10),
   AREA_SN              INTEGER
)
/

COMMENT ON TABLE OA_ORG_AREA IS
'区域基础表'
/

COMMENT ON COLUMN OA_ORG_AREA.AREA_CODE IS
'区域代码'
/

COMMENT ON COLUMN OA_ORG_AREA.AREA_NAME IS
'区域名称'
/

COMMENT ON COLUMN OA_ORG_AREA.PARENT_AREA_CODE IS
'父区域代码'
/

COMMENT ON COLUMN OA_ORG_AREA.AREA_SN IS
'区域排序'
/

/*==============================================================*/
/* Table: OA_ORG_TYPE                                           */
/*==============================================================*/
CREATE TABLE OA_ORG_TYPE 
(
   TYPE_ID              VARCHAR2(50),
   TYPE_NAME            VARCHAR2(50)         NOT NULL,
   TYPE_CODE            VARCHAR2(50)         NOT NULL
)
/

COMMENT ON TABLE OA_ORG_TYPE IS
'机构类型表'
/

COMMENT ON COLUMN OA_ORG_TYPE.TYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN OA_ORG_TYPE.TYPE_CODE IS
'类型编号'
/

/*==============================================================*/
/* Table: OA_TAG_TYPE                                           */
/*==============================================================*/
CREATE TABLE OA_TAG_TYPE 
(
   TAG_TYPE_CODE        VARCHAR2(40)         NOT NULL,
   TAG_TYPE_NAME        VARCHAR2(200),
   CONSTRAINT PK_OA_TAG_TYPE PRIMARY KEY (TAG_TYPE_CODE)
)
/

COMMENT ON TABLE OA_TAG_TYPE IS
'控件类型表'
/

COMMENT ON COLUMN OA_TAG_TYPE.TAG_TYPE_CODE IS
'tag_type_code'
/

COMMENT ON COLUMN OA_TAG_TYPE.TAG_TYPE_NAME IS
'tag_type_name'
/

/*==============================================================*/
/* View: VIEW_OA_INSTANCE                                       */
/*==============================================================*/
CREATE OR REPLACE VIEW VIEW_OA_INSTANCE(INS_ID, BUSITYPE_NAME, BUSITYPE_CODE, INS_NAME, INS_CODE, ACCEPT_TIME, ACCEPTER, ACCEPTER_ID, ORG_ID, FLOW_ID, DEF_ID, CC_FORM_INSTANCEID, BUSI_ID, LASTMODIFEDTIME, STATUS_CODE, ACTION_FORM, ACT_INSID, PROCESSID, ACTION_NAME, ACT_DEFID, ACTION_HANDERNAME, ACTION_HANDERID, TACHE_BEGIN_TIME, TACHE_END_TIME, IS_VALID) AS
SELECT
   I.INS_ID,
   B.BUSITYPE_NAME,
   I.BUSITYPE_CODE,
   I.INS_NAME,
   I.INS_CODE,
   I.ACCEPT_TIME,
   I.ACCEPTER,
   I.ACCEPTER_ID,
   I.ORG_ID,
   I.FLOW_ID,
   I.DEF_ID,
   I.CC_FORM_INSTANCEID,
   I.BUSI_ID,
   I.LASTMODIFEDTIME,
   I.STATUS_CODE,
   C.ACTION_FORM,
   C.ACT_INSID,
   C.PROCESSID,
   C.ACTION_NAME,
   C.ACT_DEFID,
   C.ACTION_HANDERNAME,
   C.ACTION_HANDERID,
   C.TACHE_BEGIN_TIME,
   C.TACHE_END_TIME,
   C.IS_VALID
FROM
   OA_FLOW_BUSITYPE B,
   OA_FLOW_INSTANCE I,
   OA_FLOW_INSWFACTION C
WHERE
   I.BUSITYPE_CODE = TRIM(B.BUSITYPE_CODE)
   AND I.INS_ID = C.INS_ID
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.BUSITYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.INS_NAME IS
'实例名称'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.INS_CODE IS
'实例编号'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACCEPT_TIME IS
'受理时间'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACCEPTER IS
'受理人'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACCEPTER_ID IS
'受理人ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ORG_ID IS
'机构ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.FLOW_ID IS
'流程ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.DEF_ID IS
'流程定义ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.CC_FORM_INSTANCEID IS
'平台实例ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.BUSI_ID IS
'业务实例ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.LASTMODIFEDTIME IS
'最后修改时间'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.STATUS_CODE IS
'类型编码'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACTION_FORM IS
'处理页面'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACT_INSID IS
'环节实例ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.PROCESSID IS
'流程实例id'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACTION_NAME IS
'活动名称'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACT_DEFID IS
'环节定义ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACTION_HANDERNAME IS
'活动处理人'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.ACTION_HANDERID IS
'活动处理人ID'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.TACHE_BEGIN_TIME IS
'活动开始时间'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.TACHE_END_TIME IS
'活动结束时间'
/

COMMENT ON COLUMN VIEW_OA_INSTANCE.IS_VALID IS
'是否有效'
/

/*==============================================================*/
/* View: VIEW_OA_TOBEWORK_LIST                                  */
/*==============================================================*/
CREATE OR REPLACE VIEW VIEW_OA_TOBEWORK_LIST(INS_ID, INS_CODE, BUSITYPE_NAME, BUSITYPE_CODE, INS_NAME, ACCEPTER, ACCEPT_TIME, LASTMODIFEDTIME, CC_FORM_INSTANCEID, BUSI_ID, FLOW_ID, DEF_ID, ACT_NAME, ACTINSID, FLOW_FORM, MGRNAME, USERNAME) AS
SELECT
   I.INS_ID,
   I.INS_CODE,
   I.BUSITYPE_NAME,
   I.BUSITYPE_CODE,
   I.INS_NAME,
   I.ACCEPTER,
   I.ACCEPT_TIME,
   I.LASTMODIFEDTIME,
   I.CC_FORM_INSTANCEID,
   I.BUSI_ID,
   I.FLOW_ID,
   I.DEF_ID,
   I.ACTION_NAME AS ACT_NAME,
   I.ACT_INSID AS ACTINSID,
   I.ACTION_FORM AS FLOW_FORM,
   U.ACTIVITYPROCESSDEFNAME AS MGRNAME,
   U.USER_NAME AS USERNAME
FROM
   VIEW_OA_INSTANCE I,
   OA_FLOW_ACTIONUSER U
WHERE I.INS_ID = U.INS_ID AND I.ACTION_HANDERNAME IS NULL AND I.STATUS_CODE = '04'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.INS_CODE IS
'实例编号'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.BUSITYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.INS_NAME IS
'实例名称'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.ACCEPTER IS
'受理人'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.ACCEPT_TIME IS
'受理时间'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.LASTMODIFEDTIME IS
'最后修改时间'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.CC_FORM_INSTANCEID IS
'平台实例ID'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.BUSI_ID IS
'业务实例ID'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.FLOW_ID IS
'流程ID'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.DEF_ID IS
'流程定义ID'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.ACT_NAME IS
'活动名称'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.ACTINSID IS
'环节实例ID'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.FLOW_FORM IS
'处理页面'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.MGRNAME IS
'环节流程实例定义名称'
/

COMMENT ON COLUMN VIEW_OA_TOBEWORK_LIST.USERNAME IS
'用户登陆名称'
/

/*==============================================================*/
/* View: VIEW_OA_WORK_LIST                                      */
/*==============================================================*/
CREATE OR REPLACE VIEW VIEW_OA_WORK_LIST(INS_ID, INS_CODE, BUSITYPE_NAME, BUSITYPE_CODE, INS_NAME, ACCEPTER, ACCEPT_TIME, LASTMODIFEDTIME, CC_FORM_INSTANCEID, BUSI_ID, FLOW_ID, DEF_ID, ACT_NAME, ACTINSID, PROCID, ACTION_DEFID, FLOW_FORM, STATUS_CODE, USERNAME, ACTIONTYPE_CODE) AS
SELECT
       I.INS_ID,
       I.INS_CODE,
       I.BUSITYPE_NAME,
       I.BUSITYPE_CODE,
       I.INS_NAME,
       I.ACCEPTER,
       I.ACCEPT_TIME,
       I.LASTMODIFEDTIME,
       I.CC_FORM_INSTANCEID,
       I.BUSI_ID,
       I.FLOW_ID,
       I.DEF_ID,
       I.ACTION_NAME AS ACT_NAME,
       I.ACT_INSID AS ACTINSID,
       I.PROCESSID AS PROCID,
       I.ACT_DEFID AS ACTION_DEFID,
       I.ACTION_FORM AS FLOW_FORM,
       I.STATUS_CODE,
       U.USER_NAME AS USERNAME,
        (SELECT W.ACTIONTYPE_CODE
          FROM OA_FLOW_WFACTION W
         WHERE W.DEF_ID = I.DEF_ID
           AND W.ACTION_DEFID = I.ACT_DEFID) AS ACTIONTYPE_CODE
  FROM VIEW_OA_INSTANCE I,
       OA_FLOW_ACTIONUSER U
 WHERE I.INS_ID = U.INS_ID AND I.ACTION_HANDERNAME IS NULL AND I.STATUS_CODE != '04' AND U.IS_HANDLE='1' AND I.ACT_INSID = U.ACTIVITY
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.INS_ID IS
'实例ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.INS_CODE IS
'实例编号'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.BUSITYPE_NAME IS
'类型名称'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.BUSITYPE_CODE IS
'类型编码'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.INS_NAME IS
'实例名称'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.ACCEPTER IS
'受理人'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.ACCEPT_TIME IS
'受理时间'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.LASTMODIFEDTIME IS
'最后修改时间'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.CC_FORM_INSTANCEID IS
'平台实例ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.BUSI_ID IS
'业务实例ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.FLOW_ID IS
'流程ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.DEF_ID IS
'流程定义ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.ACT_NAME IS
'活动名称'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.ACTINSID IS
'环节实例ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.PROCID IS
'流程实例id'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.ACTION_DEFID IS
'环节定义ID'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.FLOW_FORM IS
'处理页面'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.STATUS_CODE IS
'类型编码'
/

COMMENT ON COLUMN VIEW_OA_WORK_LIST.USERNAME IS
'用户登陆名称'
/

/*==============================================================*/
/* View: V_PROCESS_CONFIG                                       */
/*==============================================================*/
CREATE OR REPLACE VIEW V_PROCESS_CONFIG AS
SELECT DISTINCT B.DEF_ID AS PROCESS_CONFIG_ID,
B.PACKAGE_ID || '#' || B.FLOW_VERSION || '#' || B.FLOW_DEFID AS PROCESS_NAME,
B.FLOW_ID AS MODULE_ID,
 'module' AS APP_ID,
 A.ACTION_DEFID AS ACTIVITY_ID,
 C.PROPERTY_NAME AS PROPERTY_NAME,
 CASE
         WHEN C.PROPERTY_NAME = 'ACTIVITY_ALIAS' THEN
              A.ACTION_ALIAS
         WHEN C.PROPERTY_NAME = 'ACTIVITY_PARTICIPANT' THEN
              CASE
              WHEN  TO_CHAR((SELECT WM_CONCAT(U.USER_NAME) FROM OA_FLOW_WFACTUSER U WHERE U.ACTION_ID = A.ACTION_ID)) IS NULL THEN
                   ''
              ELSE
              '<ExtendedAttributes><ExtendedAttribute Name="User" Value="' || TO_CHAR((SELECT WM_CONCAT(U.USER_NAME) FROM OA_FLOW_WFACTUSER U WHERE U.ACTION_ID = A.ACTION_ID)) || '"/></ExtendedAttributes>'
              END
         WHEN C.PROPERTY_NAME = 'ACTIVITY_LIMIT' THEN
              A.ACTION_LIMIT || A.LIMIT_UNIT
         WHEN C.PROPERTY_NAME = 'DYNAMICPERFORMER' THEN
              CASE W.ISSHOWUSER
               WHEN 'Y' THEN
                'true'
               ELSE
                'true'
                END
          WHEN C.PROPERTY_NAME  = 'AUTOASSIGNMENT' THEN
          W.AUTOASSIGNMENT
       END AS PROPERTY_VALUE
  FROM OA_FLOW_WFACTION A LEFT JOIN OA_FLOW_WFACTIONEXT W ON A.ACTION_ID = W.ACTION_ID, OA_FLOW_DEFINFO B, ACTPROPERTIES C
 WHERE A.DEF_ID = B.DEF_ID
   AND B.IS_VALID = 'Y'
/

ALTER TABLE OA_FLOW_ACTIONFROMDEFID
   ADD CONSTRAINT FK_FK_OA_FLOW_WFACTION_4 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FLOW_WFACTION (ACTION_ID)
/

ALTER TABLE OA_FLOW_ACTIONTREECONFIG
   ADD CONSTRAINT FK_OA_FLOW_WFACTION_2 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FLOW_WFACTION (ACTION_ID)
/

ALTER TABLE OA_FLOW_BASEINFO
   ADD CONSTRAINT FK_OA_FLOW_BUSITYPE_1 FOREIGN KEY (BUSITYPE_CODE)
      REFERENCES OA_FLOW_BUSITYPE (BUSITYPE_CODE)
/

ALTER TABLE OA_FLOW_DEFINFO
   ADD CONSTRAINT FK_OA_FLOW_BASEINFO_1 FOREIGN KEY (FLOW_ID)
      REFERENCES OA_FLOW_BASEINFO (FLOW_ID)
/

ALTER TABLE OA_FLOW_INSTANCE
   ADD CONSTRAINT FK_OA_FLOW_STATUS_1 FOREIGN KEY (STATUS_CODE)
      REFERENCES OA_FLOW_STATUS (STATUS_CODE)
/

ALTER TABLE OA_FLOW_WFACTION
   ADD CONSTRAINT FK_OA_FLOW_DEFINFO FOREIGN KEY (DEF_ID)
      REFERENCES OA_FLOW_DEFINFO (DEF_ID)
/

ALTER TABLE OA_FLOW_WFACTIONEXT
   ADD CONSTRAINT FK_FK_OA_FLOW_WFACTION_3 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FLOW_WFACTION (ACTION_ID)
/

ALTER TABLE OA_FLOW_WFACTUSER
   ADD CONSTRAINT FK_OA_FLOW_WFACTION_1 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FLOW_WFACTION (ACTION_ID)
/

ALTER TABLE OA_FORM_BUSITYPE
   ADD CONSTRAINT FK_OA_MD_TABLE_2 FOREIGN KEY (TABLE_ID)
      REFERENCES OA_MD_TABLE (TABLE_ID)
/

ALTER TABLE OA_WORD_TEXTINPUT
   ADD CONSTRAINT FK_OA_WORD__REFERENCE_OA_WORD_ FOREIGN KEY (TEMPLATE_ID)
      REFERENCES OA_WORD_TEMPLATE (TEMPLATE_ID)
/

ALTER TABLE OA_ACT_COL_STAUTS
   ADD CONSTRAINT FK_OA_FLOW_WFACTION_5 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FLOW_WFACTION (ACTION_ID)
/

ALTER TABLE OA_ACT_TEXT_STAUTS
   ADD CONSTRAINT FK_OA_FLOW_WFACTION_6 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FLOW_WFACTION (ACTION_ID)
/

ALTER TABLE OA_COL_STAUTS_CONTORL
   ADD CONSTRAINT FK_OA_FORM_BUSITYPE_2 FOREIGN KEY (BUSITYPE_CODE)
      REFERENCES OA_FORM_BUSITYPE (BUSITYPE_CODE)
/

ALTER TABLE OA_FORM_TAG_CONFIG
   ADD CONSTRAINT FK_OA_FORM_CONFIG FOREIGN KEY (FORM_ID)
      REFERENCES OA_FORM_CONFIG (FORM_ID)
/

ALTER TABLE OA_FORM_TAG_CONFIG
   ADD CONSTRAINT FK_OA_TAG_TYPE_1 FOREIGN KEY (TAG_TYPE_ID)
      REFERENCES OA_TAG_TYPE (TAG_TYPE_CODE)
/

ALTER TABLE OA_MD_COLUMNS
   ADD CONSTRAINT FK_OA_MD_CO_REFERENCE_OA_MD_TA FOREIGN KEY (TABLE_ID)
      REFERENCES OA_MD_TABLE (TABLE_ID)
/


CREATE OR REPLACE PROCEDURE COPYFLOWINFO(NEW_DEF_ID IN VARCHAR2,OLD_DEF_ID VARCHAR2,OLD_TABLE_ID VARCHAR2)
IS
/**继承老版本配置信息
 *作者：戴连春
 *日期：2013-06-18
 *   @PARAM  NEW_DEF_ID 新的流程定义ID
 *   @PARAM  OLD_DEF_ID 要被复制的流程定义ID
 *   @PARAM  OLD_TABLE_ID   旧的业务表ID
 *
 */
 --判断要被复制的两个流程的业务表ID是一样的标记
  V_FLAG NUMBER;
  
  --要复制的活动ID
  CURSOR OLD_ACTION_CURSOR IS 
    SELECT A.ACTION_ID AS NEW_ACTION_ID, B.ACTION_ALIAS,  
    B.ACTION_LIMIT,  B.LIMIT_UNIT,  B.REMARK 
     FROM OA_FLOW_WFACTION A, OA_FLOW_WFACTION B
    WHERE A.ACTION_DEFID = B.ACTION_DEFID
     AND A.DEF_ID = NEW_DEF_ID
     AND B.DEF_ID = OLD_DEF_ID;    
BEGIN
  
--继承流程活动用户信息
INSERT INTO OA_FLOW_WFACTUSER
  (WFACTUSER_ID, ACTION_ID, USER_ID, USER_NAME, ACTUSER_TYPE, CREATE_TIME)
  SELECT SYS_GUID(),
         A.ACTION_ID,
         C.USER_ID,
         C.USER_NAME,
         C.ACTUSER_TYPE,
         SYSDATE
    FROM OA_FLOW_WFACTION A, OA_FLOW_WFACTION B, OA_FLOW_WFACTUSER C
   WHERE A.ACTION_DEFID = B.ACTION_DEFID
     AND B.ACTION_ID = C.ACTION_ID
     AND  A.DEF_ID =NEW_DEF_ID 
     AND B.DEF_ID =OLD_DEF_ID ;

--继承活动树配置信息
INSERT INTO OA_FLOW_ACTIONTREECONFIG
  (CONFIG_ID, ACTION_ID, TREE_ROLE, TREE_NODETYPE)
  SELECT SYS_GUID(), A.ACTION_ID, C.TREE_ROLE, C.TREE_NODETYPE
    FROM OA_FLOW_WFACTION A, OA_FLOW_WFACTION B, OA_FLOW_ACTIONTREECONFIG C
   WHERE A.ACTION_DEFID = B.ACTION_DEFID
     AND B.ACTION_ID = C.ACTION_ID
  AND  A.DEF_ID =NEW_DEF_ID 
     AND B.DEF_ID =OLD_DEF_ID;


--继承活动扩展表信息
INSERT INTO OA_FLOW_WFACTIONEXT
  (ACTIONEXT_ID,
   ACTION_ID,
   ISSHOWUSER,
   ISSHOWREJECT,
   CREATE_TIME,
   ISSHOWBACK,
   AUTOASSIGNMENT,
   ISSIGNJOINBYORDER)
  SELECT SYS_GUID(),
         A.ACTION_ID,
         C.ISSHOWUSER,
         C.ISSHOWREJECT,
         SYSDATE,
         C.ISSHOWBACK,
         C.AUTOASSIGNMENT,
         C.ISSIGNJOINBYORDER
    FROM OA_FLOW_WFACTION A, OA_FLOW_WFACTION B, OA_FLOW_WFACTIONEXT C
   WHERE A.ACTION_DEFID = B.ACTION_DEFID
     AND B.ACTION_ID = C.ACTION_ID
   AND  A.DEF_ID=NEW_DEF_ID 
     AND B.DEF_ID =OLD_DEF_ID;

--继承流程活动表正文状态控制表信息
INSERT INTO OA_ACT_TEXT_STAUTS
  (ID,
   ACTION_ID,
   IS_TRACE,
   IS_RED,
   IS_READONLY,
   EXTEND_ATTRIBUTE,
   EXTEND_METHODS)
  SELECT SYS_GUID(),
         A.ACTION_ID,
         C.IS_TRACE,
         C.IS_RED,
         C.IS_READONLY,
         C.EXTEND_ATTRIBUTE,
         C.EXTEND_METHODS
    FROM OA_FLOW_WFACTION A, OA_FLOW_WFACTION B, OA_ACT_TEXT_STAUTS C
   WHERE A.ACTION_DEFID = B.ACTION_DEFID
     AND B.ACTION_ID = C.ACTION_ID
     AND A.DEF_ID=NEW_DEF_ID
     AND B.DEF_ID =OLD_DEF_ID;

 --循环复制动作基本信息
  FOR C_ACTION_CURSOR IN OLD_ACTION_CURSOR LOOP       
    UPDATE OA_FLOW_WFACTION
       SET ACTION_ALIAS = C_ACTION_CURSOR.ACTION_ALIAS,
           ACTION_LIMIT = C_ACTION_CURSOR.ACTION_LIMIT,
           LIMIT_UNIT = C_ACTION_CURSOR.LIMIT_UNIT,
           REMARK = C_ACTION_CURSOR.REMARK     
    WHERE ACTION_ID = C_ACTION_CURSOR.NEW_ACTION_ID ;    
  END LOOP;

     --判断两个流程的业务表是否一样
   SELECT COUNT(*)
     INTO V_FLAG
     FROM OA_MD_TABLE_BUSINESS_MAPPING A
    WHERE EXISTS (SELECT *
             FROM OA_FLOW_BASEINFO B
            WHERE A.BUSITYPE_CODE = B.BUSITYPE_CODE
              AND EXISTS (SELECT FLOW_ID
                     FROM OA_FLOW_DEFINFO C
                    WHERE C.FLOW_ID = B.FLOW_ID
                      AND C.DEF_ID = NEW_DEF_ID))
      AND A.TABLE_ID = OLD_TABLE_ID;  
                     
  --如果两个流程配置的 ‘业务表’是一样的，则复制配置信息
  IF(V_FLAG > 0) THEN

   INSERT INTO OA_ACT_COL_STAUTS
   (ID, ACTION_ID, TABLE_ID, TABLE_CODE, COLUMN_ID, COLUMN_CODE, READONLY, HIDDEN, DISABLE, REQUIRED)
   SELECT SYS_GUID(),
         A.ACTION_ID,
         C.TABLE_ID, C.TABLE_CODE, C.COLUMN_ID, C.COLUMN_CODE, C.READONLY, C.HIDDEN, C.DISABLE, C.REQUIRED
    FROM OA_FLOW_WFACTION A, OA_FLOW_WFACTION B, OA_ACT_COL_STAUTS C
   WHERE A.ACTION_DEFID = B.ACTION_DEFID
     AND B.ACTION_ID = C.ACTION_ID
     AND  A.DEF_ID =NEW_DEF_ID 
     AND B.DEF_ID =OLD_DEF_ID ;
 END IF;
 END  COPYFLOWINFO;
/


CREATE OR REPLACE FUNCTION OA_GETACTION_INDEX(V_PROCESSID IN VARCHAR2,
                                              V_ACT_INSID IN VARCHAR2)
RETURN VARCHAR2 AS
  ACT_INDEX VARCHAR2(50);
BEGIN
  SELECT ACT_INDEX
    INTO ACT_INDEX
    FROM (SELECT ROW_NUMBER() OVER(ORDER BY W.TACHE_BEGIN_TIME DESC) ACT_INDEX,
                 W.*
            FROM VIEW_OA_INSTANCE W
           WHERE W.PROCESSID = V_PROCESSID
             AND W.ACTION_HANDERNAME IS NOT NULL AND W.IS_VALID = 'Y')
   WHERE ACT_INSID = V_ACT_INSID
     AND STATUS_CODE = '01';
  RETURN(ACT_INDEX);
END;
/


CREATE OR REPLACE FUNCTION OA_GETORGLISTBYUSERIDS(SUBUSERIDS IN VARCHAR2)
RETURN VARCHAR2 AS
   RS CLOB;
         CURSOR SUBUSERIDLIST IS (SELECT COLUMN_VALUE USER_ID FROM TABLE(OA_SPLIT(SUBUSERIDS)));
         CC SUBUSERIDLIST%rowtype;
         orgids varchar2(3000);
         allorgids clob;
     begin
       open subUseridList;
       loop
         fetch subUseridList into cc;
         exit when subUseridList%NOTFOUND;
         SELECT WM_CONCAT(ORG.ORG_ID) INTO ORGIDS
          FROM TD_SM_ORGANIZATION ORG
              START WITH ORG.ORG_ID = (SELECT OU.ORG_ID FROM TD_SM_ORGUSER OU WHERE OU.USER_ID = CC.USER_ID)
          CONNECT BY PRIOR ORG.PARENT_ID = ORG.ORG_ID;
          IF ALLORGIDS IS NULL THEN
            ALLORGIDS := ORGIDS;
          ELSE
            ALLORGIDS := ALLORGIDS||','||ORGIDS;
          END IF;
       END LOOP;
      CLOSE SUBUSERIDLIST;
      SELECT WM_CONCAT(''''||ORG_ID||'''') INTO RS FROM TD_SM_ORGANIZATION O WHERE INSTR(ALLORGIDS,O.ORG_ID)>0;
       RETURN(RS);
     END;
/


CREATE OR REPLACE FUNCTION OA_SPLIT(P_LIST VARCHAR2,

   P_SEP VARCHAR2 := ',')
RETURN OA_TYPE_SPLIT PIPELINED

 IS

   L_IDX  PLS_INTEGER;

   V_LIST  VARCHAR2(4000) := P_LIST;

BEGIN

   LOOP

      L_IDX := INSTR(V_LIST,P_SEP);

      IF L_IDX > 0 THEN

          PIPE ROW(SUBSTR(V_LIST,1,L_IDX-1));

          V_LIST := SUBSTR(V_LIST,L_IDX+LENGTH(P_SEP));

      ELSE

          PIPE ROW(V_LIST);

          EXIT;

      END IF;

   END LOOP;

   RETURN;

END OA_SPLIT;
/

DROP view V_OA_BCODE_TABLE_MAP;

/*==============================================================*/
/* View: V_OA_BCODE_TABLE_MAP                                   */
/*==============================================================*/
CREATE OR REPLACE VIEW V_OA_BCODE_TABLE_MAP AS
SELECT T.BUSITYPE_NAME AS BUSITYPE_CODE , T.TABLE_ID AS TABLE_ID FROM  OA_FORM_BUSITYPE T
UNION ALL
SELECT TM.BUSITYPE_CODE AS BUSITYPE_CODE, TM.TABLE_ID AS TABLE_ID FROM OA_MD_TABLE_BUSINESS_MAPPING TM
WITH READ ONLY;

COMMENT ON COLUMN V_OA_BCODE_TABLE_MAP.BUSITYPE_CODE IS
'类型名称';

COMMENT ON COLUMN V_OA_BCODE_TABLE_MAP.TABLE_ID IS
'表ID';


DROP TABLE OA_SFW_USERLISTCONF CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_SFW_USERLISTCONF                                   */
/*==============================================================*/
CREATE TABLE OA_SFW_USERLISTCONF 
(
   ID                   VARCHAR(50)          NOT NULL,
   LIST_TYPE            VARCHAR(30)          NOT NULL,
   EXTABLE              VARCHAR(30),
   COLUMN_LIST          VARCHAR(200),
   USER_ID              VARCHAR(50)          NOT NULL,
   CONSTRAINT PK_OA_SFW_USERLISTCONF PRIMARY KEY (ID)
);

COMMENT ON TABLE OA_SFW_USERLISTCONF IS
'收发文登记薄用户列表配置表';

COMMENT ON COLUMN OA_SFW_USERLISTCONF.LIST_TYPE IS
'列表类型';

COMMENT ON COLUMN OA_SFW_USERLISTCONF.EXTABLE IS
'绑定的扩展表';

COMMENT ON COLUMN OA_SFW_USERLISTCONF.COLUMN_LIST IS
'绑定的相应的表的字段集合';

COMMENT ON COLUMN OA_SFW_USERLISTCONF.USER_ID IS
'用户id';

--删除流程实例存储过程
create or replace procedure deleteFlowInsInfo(d_ins_id in varchar2) is
begin

--环节任务表 
delete  from  OA_FLOW_ACTIONUSER where ins_id = d_ins_id;
--流程活动业务表
delete  from OA_FLOW_INSWFACTION  where ins_id = d_ins_id;
--文件传阅表
delete  from OA_CIRCULARIZE_FLOW  where ins_id = d_ins_id;
--意见列表
delete  from OA_FLOW_INSVIEWLIST  where ins_id = d_ins_id;
--流程实例表
delete  from  OA_FLOW_INSTANCE  where ins_id = d_ins_id;

end deleteFlowInsInfo;
/