-- Add/modify columns 
alter table OA_MD_TABLE modify PARENT_TABLE_ID VARCHAR2(50);

ALTER TABLE OA_FORM_ACTION
   DROP CONSTRAINT FK_OA_FORM_BUSITYPE_3;

ALTER TABLE OA_FORM_BUSITYPE
   DROP CONSTRAINT FK_OA_MD_TABLE_2;

DROP TABLE OA_FORM_BUSITYPE CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_FORM_BUSITYPE                                      */
/*==============================================================*/
CREATE TABLE OA_FORM_BUSITYPE 
(
   BUSITYPE_CODE        VARCHAR2(50)         NOT NULL,
   BUSITYPE_NAME        VARCHAR2(50)         NOT NULL,
   TYPE_DESC            VARCHAR2(200),
   IS_VALID             CHAR(1)              DEFAULT 'Y' NOT NULL,
   TABLE_ID             VARCHAR2(50),
   CONSTRAINT PK_OA_FORM_BUSITYPE PRIMARY KEY (BUSITYPE_CODE)
);

COMMENT ON TABLE OA_FORM_BUSITYPE IS
'表单业务类型表';

COMMENT ON COLUMN OA_FORM_BUSITYPE.BUSITYPE_CODE IS
'类型编码';

COMMENT ON COLUMN OA_FORM_BUSITYPE.BUSITYPE_NAME IS
'类型名称';

COMMENT ON COLUMN OA_FORM_BUSITYPE.TYPE_DESC IS
'类型描述';

COMMENT ON COLUMN OA_FORM_BUSITYPE.IS_VALID IS
'是否有效';

COMMENT ON COLUMN OA_FORM_BUSITYPE.TABLE_ID IS
'表ID';

ALTER TABLE OA_FORM_BUSITYPE
   ADD CONSTRAINT FK_OA_MD_TABLE_2 FOREIGN KEY (TABLE_ID)
      REFERENCES OA_MD_TABLE (TABLE_ID);

ALTER TABLE OA_FORM_ACTION
   DROP CONSTRAINT FK_OA_FORM_BUSITYPE_3;

ALTER TABLE OA_COL_STAUTS_CONTORL
   DROP CONSTRAINT FK_OA_FORM_ACTION_1;

DROP TABLE OA_FORM_ACTION CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_FORM_ACTION                                        */
/*==============================================================*/
CREATE TABLE OA_FORM_ACTION 
(
   ACTION_ID            VARCHAR2(50)         NOT NULL,
   ACTION_CODE          VARCHAR2(50)         NOT NULL,
   ACTION_NAME          VARCHAR2(50)         NOT NULL,
   BUSITYPE_CODE        VARCHAR2(50),
   BUSITYPE_NAME        VARCHAR2(50),
   ACTION_DESC          VARCHAR2(200),
   IS_VALID             CHAR(1)              DEFAULT 'Y' NOT NULL,
   CREATE_TIME          DATE,
   CONSTRAINT PK_OA_FORM_ACTION PRIMARY KEY (ACTION_ID)
);

COMMENT ON TABLE OA_FORM_ACTION IS
'表单环节定义表';

COMMENT ON COLUMN OA_FORM_ACTION.ACTION_ID IS
'环节ID 主键';

COMMENT ON COLUMN OA_FORM_ACTION.ACTION_CODE IS
'环节编码';

COMMENT ON COLUMN OA_FORM_ACTION.ACTION_NAME IS
'环节名称';

COMMENT ON COLUMN OA_FORM_ACTION.BUSITYPE_CODE IS
'业务类型';

COMMENT ON COLUMN OA_FORM_ACTION.BUSITYPE_NAME IS
'业务类型名称';

COMMENT ON COLUMN OA_FORM_ACTION.ACTION_DESC IS
'类型描述';

COMMENT ON COLUMN OA_FORM_ACTION.IS_VALID IS
'是否有效';

COMMENT ON COLUMN OA_FORM_ACTION.CREATE_TIME IS
'创建时间';

ALTER TABLE OA_FORM_ACTION
   ADD CONSTRAINT FK_OA_FORM_BUSITYPE_3 FOREIGN KEY (BUSITYPE_CODE)
      REFERENCES OA_FORM_BUSITYPE (BUSITYPE_CODE);

ALTER TABLE OA_COL_STAUTS_CONTORL
   DROP CONSTRAINT FK_OA_FORM_ACTION_1;

DROP TABLE OA_COL_STAUTS_CONTORL CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_COL_STAUTS_CONTORL                                 */
/*==============================================================*/
CREATE TABLE OA_COL_STAUTS_CONTORL 
(
   ID                   VARCHAR2(50)         NOT NULL,
   ACTION_ID            VARCHAR2(50),
   TABLE_ID             VARCHAR2(50),
   TABLE_CODE           VARCHAR2(50)         NOT NULL,
   COLUMN_ID            VARCHAR2(50)         NOT NULL,
   COLUMN_CODE          VARCHAR2(50)         NOT NULL,
   READONLY             CHAR(1)              DEFAULT '0' NOT NULL,
   HIDDEN               CHAR(1)              DEFAULT '0' NOT NULL,
   DISABLE              CHAR(1)              DEFAULT '0' NOT NULL,
   REQUIRED             CHAR(1),
   REMARK1              VARCHAR2(500),
   CONSTRAINT PK_OA_COL_STAUTS_CONTORL PRIMARY KEY (ID)
);

COMMENT ON TABLE OA_COL_STAUTS_CONTORL IS
'表单元素状态表(环节字段状态表)';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.ID IS
'状态id';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.ACTION_ID IS
'环节ID 主键';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.TABLE_ID IS
'表ID';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.TABLE_CODE IS
'库表名称';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.COLUMN_ID IS
'字段id';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.COLUMN_CODE IS
'字段名称';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.READONLY IS
'是否只读';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.HIDDEN IS
'是否隐藏';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.DISABLE IS
'是否禁用';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.REQUIRED IS
'是否必填';

COMMENT ON COLUMN OA_COL_STAUTS_CONTORL.REMARK1 IS
'扩展字段';

ALTER TABLE OA_COL_STAUTS_CONTORL
   ADD CONSTRAINT FK_OA_FORM_ACTION_1 FOREIGN KEY (ACTION_ID)
      REFERENCES OA_FORM_ACTION (ACTION_ID);
      