DROP TABLE OA_WORD_NUMBER CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_WORD_NUMBER                                        */
/*==============================================================*/
CREATE TABLE OA_WORD_NUMBER 
(
   BUSI_ID              VARCHAR2(50)         NOT NULL,
   NUMBER_TYPE          VARCHAR2(50)         NOT NULL,
   NUMBER_YEAR          VARCHAR2(50)         NOT NULL,
   NUMBER_CODE          NUMBER               NOT NULL,
   NUMBER_TITLE         VARCHAR2(200),
   ARCHIVE_TITLE        VARCHAR2(200),
   ARCHIVE_DATE         VARCHAR2(50),
   ARCHIVE_USER         VARCHAR2(50),
   IS_PAPER             VARCHAR2(50),
   ARCHIVE_TYPE         VARCHAR2(50),
   CONSTRAINT PK_OA_WORD_NUMBER PRIMARY KEY (BUSI_ID, NUMBER_TYPE, NUMBER_YEAR, NUMBER_CODE)
);

COMMENT ON TABLE OA_WORD_NUMBER IS
'公文编号';

COMMENT ON COLUMN OA_WORD_NUMBER.BUSI_ID IS
'业务ID';

COMMENT ON COLUMN OA_WORD_NUMBER.NUMBER_TYPE IS
'编号类型';

COMMENT ON COLUMN OA_WORD_NUMBER.NUMBER_YEAR IS
'编号年份';

COMMENT ON COLUMN OA_WORD_NUMBER.NUMBER_CODE IS
'编号号码';

COMMENT ON COLUMN OA_WORD_NUMBER.NUMBER_TITLE IS
'编号标题';

COMMENT ON COLUMN OA_WORD_NUMBER.ARCHIVE_TITLE IS
'公文标题';

COMMENT ON COLUMN OA_WORD_NUMBER.ARCHIVE_DATE IS
'日期';

COMMENT ON COLUMN OA_WORD_NUMBER.ARCHIVE_USER IS
'申请人';

COMMENT ON COLUMN OA_WORD_NUMBER.IS_PAPER IS
'是否纸质';

COMMENT ON COLUMN OA_WORD_NUMBER.ARCHIVE_TYPE IS
'类型';
