package com.chinacreator.xtbg.core.codegenerator.generator.SqlUtilGenerator.jsp;

import com.chinacreator.xtbg.core.codegenerator.entity.ClassProperty;
import com.chinacreator.xtbg.core.codegenerator.entity.ColumnProperty;
import com.chinacreator.xtbg.core.codegenerator.generator.JspPageGenerator;
import com.chinacreator.xtbg.core.codegenerator.util.CodeConstant;


public class GeneratorListJspCode implements JspPageGenerator {
	@Override
	public String generateJava(ClassProperty classProperty) {
		StringBuffer code = new StringBuffer();
		code.append("<%@ page contentType=\"text/html; charset=UTF-8\"%>\r\n");
		code.append("<%@ page import=\"com.chinacreator.security.AccessControl\"%>\r\n");
		code.append("<%\r\n");
		code.append("    AccessControl accesscontroler = AccessControl.getAccessControl();\r\n");
		code.append("    accesscontroler.checkAccess(request, response);\r\n");
		code.append("    String path = request.getContextPath();\r\n");
		code.append("%>\r\n");
		return code.toString();
	}
	@Override
	public String generateHeader(ClassProperty classProperty) {
		StringBuffer code = new StringBuffer();
		code.append("<!DOCTYPE HTML>\r\n");
		code.append("<html>\r\n");
		code.append("<head>\r\n");
		code.append("<title>"+classProperty.getTableChiName()+"列表页面</title>\r\n");
		code.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
		code.append("<!-- 引入jQuery -->\r\n");
		code.append("<script type=\"text/javascript\" src=\"../../resources/plug/jquery-ui-1.8.17.custom/js/jquery-1.7.1.min.js\"></script>\r\n");
		code.append("<!-- 引入jQuery UI -->\r\n");
		code.append("<script src=\"../../resources/plug/jquery-ui-1.8.17.custom/js/jquery-ui-1.8.17.custom.min.js\" type=\"text/javascript\"></script>\r\n");
		code.append("<!-- 引入jGrid -->\r\n");
		code.append("<script src=\"../../resources/plug/jquery.jqGrid-4.3.1/js/i18n/grid.locale-en.js\" type=\"text/javascript\"></script>\r\n");
		code.append("<script src=\"../../resources/plug/jquery.jqGrid-4.3.1/js/jquery.jqGrid.min.js\" type=\"text/javascript\"></script>\r\n");
		code.append("<!-- 引入其它 -->\r\n");
		code.append("<script src=\"../../resources/plug/ifrom/js/ifrom-ui-alert.1.1.js\" type=\"text/javascript\"></script>\r\n");
		code.append("<script type=\"text/javascript\" src=\"../../resources/util/public.js\"></script>\r\n");
		code.append("<script type=\"text/javascript\" src=\"../../resources/plug/ifrom/js/ifrom-tools.1.1.js\"></script>\r\n");
		return code.toString();
	}
	@Override
	public String generateScript(ClassProperty classProperty) {
		StringBuffer code = new StringBuffer();
		code.append("<script type=\"text/javascript\">\r\n");
		code.append("$(function(){\r\n");
		code.append("	$(document).keydown(function(){\r\n");
		code.append("		if(event.keyCode == 13){\r\n");
		code.append("			objectSearch();\r\n");
		code.append("		}\r\n");
		code.append("	});\r\n");
		code.append("	\r\n");
		code.append("	$(\"#gridTable\").jqGrid({\r\n");
		code.append("		//servletBean.xml示例配置，id请自行修改，配完请删除此注释！菜单配置请看页面最下面！\r\n");
		code.append("		//<className id=\"auto_"+CodeConstant.getClassNameForList(classProperty)+"\">"+classProperty.getClassPackage()+"."+CodeConstant.PACKAGE_LIST+"."+CodeConstant.getClassNameForList(classProperty)+"</className>\r\n");
		code.append("		url: '<%= path %>' + '/pubListServlet?classNameId=auto_"+CodeConstant.getClassNameForList(classProperty)+"',  //commonListServlet列表公共的servlet,classNameId在servletBean.xml文件中配置要调用的类,isPage:是否翻页(true,false),默认为true\r\n");
		code.append("		datatype: \"json\",\r\n");
		code.append("		mtype: \"POST\",\r\n");
		code.append("		height: \"100%\",\r\n");
		code.append("		autowidth: true,\r\n");
		code.append("		colModel: [ //最重要的数组之一，用于设定各列的参数\r\n");
		for(int i = 0;i<classProperty.getColumnProperty().size();i++){
			ColumnProperty column = classProperty.getColumnProperty().get(i);
			String isHidden = "hidden:false";
			if(column.isPrimarykey()){
				isHidden = "hidden:true";
			}
			if(i != classProperty.getColumnProperty().size()-1){
				code.append("			{label:'"+column.getComments()+"',name: '"+column.getCode()+"',index: '"+column.getCode()+"',width: '100',"+isHidden+"},\r\n");
			} else {
				code.append("			{label:'"+column.getComments()+"',name: '"+column.getCode()+"',index: '"+column.getCode()+"',width: '100',"+isHidden+"}\r\n");
			}
		}
		code.append("		],\r\n");
		code.append("		sortname: '',\r\n");
		code.append("		sortorder: 'desc',\r\n");
		code.append("		viewrecords: true,\r\n");
		code.append("		rowNum: 15,\r\n");
		code.append("		rowList: [10, 20, 30],\r\n");
		code.append("		gridComplete: function() {\r\n");
		code.append("			var ids = $(\"#gridTable\").getDataIDs(); //jqGrid('getDataIDs');\r\n");
		code.append("			for (var i = 0; i < ids.length; i++) {\r\n");
		code.append("				var cl = ids[i];\r\n");
		code.append("				var model = jQuery(\"#gridTable\").jqGrid('getRowData', cl);\r\n");
		code.append("			}\r\n");
		code.append("		},\r\n");
		code.append("		jsonReader: { //这又是一个数组，用来设定如何解析从Server端发回来的json数据\r\n");
		code.append("			repeatitems: false\r\n");
		code.append("		},\r\n");
		code.append("		pagerintoolbar:true,//上面的分页条\r\n");
		code.append("		pagerinBottombar:true,//下面的分页条\r\n");
		code.append("		search : toParamJosn(),\r\n");
		code.append("		prmNames: { //这是一个数组，用于设置jqGrid将要向Server传递的参数名称\r\n");
		code.append("			rows: \"rows\",\r\n");
		code.append("			sort: \"sidx\",\r\n");
		code.append("			order: \"sord\",\r\n");
		code.append("			search : \"search\"\r\n");
		code.append("		},\r\n");
		code.append("		toolbar: [true,\"top\",\"<input class='but_y_01' id='add' type='button' onclick='openInfoPage()' value='新增'/>\"+\r\n");
		code.append("							\"<input class='but_y_01' id='delete' type='button' onclick='deleteData()' value='删除'/>\"],\r\n");
		code.append("		multiselect: true,\r\n");
		code.append("		onCellSelect:function(rowid,iCol){\r\n");
		code.append("			if(iCol != 0){\r\n");
		code.append("				editItem(rowid);\r\n");
		code.append("			}\r\n");
		code.append("		}\r\n");
		code.append("	}).navGrid('#gridPager', {\r\n");
		code.append("		edit: false,\r\n");
		code.append("		add: false,\r\n");
		code.append("		del: false,\r\n");
		code.append("		search:false,\r\n");
		code.append("		refresh:false\r\n");
		code.append("	});\r\n");
		code.append("});\r\n");
		code.append("\r\n");
		code.append("var objectSearch = function() {\r\n");
		code.append("	var sdata = { //构建查询需要的参数 \r\n");
		code.append("		paramJson: toParamJosn()\r\n");
		code.append("	}; //获得当前postData选项的值  \r\n");
		code.append("	var postData = $(\"#gridTable\").jqGrid(\"getGridParam\", \"postData\")\r\n"); //将查询参数融入postData选项对象  \r\n");
		code.append("	$.extend(postData, sdata);\r\n");
		code.append("	$(\"#gridTable\").jqGrid(\"setGridParam\", {\r\n");
		code.append("		search: true // 将jqGrid的search选项设为true  \r\n");
		code.append("	}).trigger(\"reloadGrid\", [{\r\n");
		code.append("		page: 1\r\n");
		code.append("	}]); //重新载入Grid表格，以使上述设置生效 \r\n");
		code.append("}\r\n");
		code.append("function clearData(){	//重置搜索\r\n");
		code.append("	//设置重置表单\r\n");
		code.append("	//$(\"#name\").val(\"\");\r\n");
		code.append("	objectSearch();\r\n");
		code.append(" }\r\n");
		code.append("function toParamJosn(){\r\n");
		code.append("	var name = $(\"#name\").val();\r\n");
		code.append("	var str = \"{'name':'\"+descape(name)+\"'}\";\r\n");
		code.append("	return escape(str);\r\n");
		code.append("}\r\n");
		code.append("\r\n");
		code.append("function openInfoPage(){\r\n");
		code.append("    var tmp_subid = \""+classProperty.getClassName().toLowerCase()+"_"+"add\";\r\n");
		code.append("    var url = \""+CodeConstant.getClassNameForJspInfo(classProperty)+".jsp?subid=\"+tmp_subid\r\n");
		code.append("    //var url = \"<%=path%>\"+\""+CodeConstant.getJspUrl(classProperty.getJspPath())+"/"+CodeConstant.PACKAGE_JSP+"/"+CodeConstant.getClassNameForJspInfo(classProperty)+".jsp?subid=\"+tmp_subid+\"&"+classProperty.getPrimaryKey()+"=\"+object."+classProperty.getPrimaryKey()+"\r\n");
		code.append("    //openAlertWindows(tmp_subid,url,'新增"+classProperty.getTableChiName()+"',600,400,'15%','15%');\r\n");
		code.append("    openWindows(tmp_subid,'新增"+classProperty.getTableChiName()+"',url,tmp_subid,false,window);\r\n");
		code.append("}\r\n");
		code.append("function editItem(rowid){\r\n");
		code.append("    var object = $(\"#gridTable\").jqGrid('getRowData', rowid);\r\n");
		code.append("    var tmp_subid = \""+classProperty.getClassName().toLowerCase()+"_"+"update\";\r\n");
		code.append("    var url = \""+CodeConstant.getClassNameForJspInfo(classProperty)+".jsp?subid=\"+tmp_subid+\"&"+classProperty.getPrimaryKey()+"=\"+object."+classProperty.getPrimaryKey()+"\r\n");
		code.append("    //var url = \"<%=path%>\"+\""+CodeConstant.getJspUrl(classProperty.getJspPath())+"/"+CodeConstant.PACKAGE_JSP+"/"+CodeConstant.getClassNameForJspInfo(classProperty)+".jsp?subid=\"+tmp_subid+\"&"+classProperty.getPrimaryKey()+"=\"+object."+classProperty.getPrimaryKey()+"\r\n");
		code.append("    //openAlertWindows(tmp_subid,url,'更新"+classProperty.getTableChiName()+"',600,220,'15%','15%');\r\n");
		code.append("    openWindows(tmp_subid,'更新"+classProperty.getTableChiName()+"',url,tmp_subid,false,window);\r\n");
		code.append("}\r\n");
		code.append("function deleteData(){\r\n");
		code.append("	var ids = \"\";\r\n");
		code.append("	var tempArrs = [];\r\n");
		code.append("	var selectedIds = $(\"#gridTable\").jqGrid(\"getGridParam\", \"selarrrow\");\r\n");
		code.append("	$(selectedIds).each(function(){\r\n");
		code.append("		var model = jQuery(\"#gridTable\").jqGrid('getRowData', this);\r\n");
		code.append("		if(!IsSpace(model."+classProperty.getPrimaryKey()+")){\r\n");
		code.append("			tempArrs.push(\"'\"+model."+classProperty.getPrimaryKey()+"+\"'\")\r\n");
		code.append("		}\r\n");
		code.append("	})\r\n");
		code.append("	ids = tempArrs.join();\r\n");
		code.append("	if (IsSpace(ids)) {\r\n");
		code.append("		alert(\"请选择要删除的记录！\");\r\n");
		code.append("	} else {\r\n");
		code.append("		var okF = function(){\r\n");
		code.append("			$.ajax({\r\n");
		code.append("				url:'"+CodeConstant.getClassNameForJspDo(classProperty)+".jsp',\r\n");
		code.append("				type:'post',dataType:'json',\r\n");
		code.append("				data:{\"method\":\""+CodeConstant.METHOD_DELETE+"\",\""+classProperty.getPrimaryKey()+"\":ids},\r\n");
		code.append("				success:function(data){\r\n");
		code.append("					if(data.code.index == 0){\r\n");
		code.append("						alert(\"删除数据成功！\");\r\n");
		code.append("						objectSearch();\r\n");
		code.append("					} else {\r\n");
		code.append("						alert(\"删除数据失败！errorCode[\"+data.code.index+\"]\");\r\n");
		code.append("					}\r\n");
		code.append("				}\r\n");
		code.append("			})\r\n");
		code.append("		}\r\n");
		code.append("		var p={\r\n");
		code.append("			headerText:'提示',\r\n");
		code.append("			okName:'确认',\r\n");
		code.append("			okFunction:okF,\r\n");
		code.append("			cancelName:'取消'\r\n");
		code.append("		};\r\n");
		code.append("		alert(\"确定要删除吗？\",p);\r\n");
		code.append("	}\r\n");
		code.append("}\r\n");
		code.append("</script>\r\n");
		return code.toString();
	}
	@Override
	public String generateBody(ClassProperty classProperty) {
		StringBuffer code = new StringBuffer();
		code.append("<body style=\"overflow-x:hidden;overflow-y:auto;\">\r\n");
		code.append("<table width=\"100%\" id=\"queryTable\">\r\n");
		code.append("		<!--代码自动生成的时候条件搜索隐藏  可自行放开 去掉display:none-->\r\n");
		code.append("		<tr style='display:none;'>\r\n");
		code.append("			<td>\r\n");
		code.append("				<!-- 查询条件选区    tabs_search_ctable(查询table样式) -->\r\n");
		code.append("				<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"tabs_search_ctable_box\">\r\n");
		code.append("						<tr>\r\n");
		code.append("							<td>\r\n");
		code.append("								<!-- 固定查询 -->\r\n");
		code.append("								<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"tabs_search_ctable\">\r\n");
		code.append("									<tr>\r\n");
		code.append("										<th width=\"90\" class=\"input_cx_title_th\">标题：</th>\r\n");
		code.append("										<td width=\"296\"  class=\"cx_title_td\">\r\n");
		code.append("											<input class=\"input_cx_title_283 \" type=\"text\" id=\"unit_name\"/>\r\n");
		code.append("										</td>\r\n");
		code.append("										<td>\r\n");
		code.append("											<input name=\"Input2\" value=\"搜索\" type=\"button\"	onclick=\"objectSearch()\" class=\"but_y_01\"/>\r\n");
		code.append("											<input name=\"Input2\" value=\"重置\" type=\"button\"	onclick=\"clearData()\" class=\"but_y_01\"/>\r\n");
		code.append("											<span id=\"selAreaImg\" class=\"all_search_condition\">\r\n");
		code.append("												<a onclick=\"hiddenOrShowSelArea('hiddenArea','selAreaImg')\" >更多搜索条件</a>\r\n");
		code.append("											</span>\r\n");
		code.append("										</td>\r\n");
		code.append("									</tr>\r\n");
		code.append("								</table>\r\n");
		code.append("							</td>\r\n");
		code.append("						</tr>	\r\n");
		code.append("						<!-- 固定查询 end-->\r\n");
		code.append("						<tr>\r\n");
		code.append("							<td>\r\n");
		code.append("								<!-- 隐藏查询 -->\r\n");
		code.append("								<table width=\"70%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"tabs_search_ctable\" id=\"hiddenArea\" style=\"display:none\">\r\n");
		code.append("									<tr>\r\n");
		code.append("										<th width=\"90\" class=\"input_cx_title_th\">标题：</th>\r\n");
		code.append("										<td width=\"296\"  class=\"cx_title_td\">\r\n");
		code.append("											<input class=\"input_cx_title_283 \" type=\"text\" id=\"name\"/>\r\n");
		code.append("										</td>\r\n");
		code.append("										<th>&nbsp;</th>\r\n");
		code.append("										<td>&nbsp;</td>\r\n");
		code.append("									</tr>\r\n");
		code.append("								</table>\r\n");
		code.append("								<!-- 隐藏查询 end-->\r\n");
		code.append("							</td>\r\n");
		code.append("						</tr>\r\n");
		code.append("				</table>\r\n");
		code.append("			</td>\r\n");
		code.append("		</tr>\r\n");
		code.append("		<tr>\r\n");
		code.append("			<td>\r\n");
		code.append("				<div class=\"cGridArea\" >\r\n");
		code.append("					<table id=\"gridTable\"></table>\r\n");
		code.append("					<div id=\"gridPager\"></div>\r\n");
		code.append("				</div>\r\n");
		code.append("			</td>\r\n");
		code.append("		</tr>\r\n");
		code.append("	</table>\r\n");
		code.append("</body>\r\n");
		code.append("</html>\r\n");
		code.append("<!-- 菜单配置示例,菜单id请自行修改 配完请删此注释 module.xml \r\n");
		code.append("<item datasource=\"bspf\" default=\"false\" id=\"auto_"+CodeConstant.getClassNameForJspList(classProperty)+"\" isdelete=\"true\" isedit=\"true\" name=\""+classProperty.getTableChiName()+"\">\r\n");
		code.append("    <workspace>\r\n");
		code.append("        <toolbar />\r\n");
		code.append("        <content>"+CodeConstant.getJspUrl(classProperty.getJspPath())+"/jsp/"+CodeConstant.getClassNameForJspList(classProperty)+".jsp</content>\r\n");
		code.append("    </workspace>\r\n");
		code.append("</item>\r\n");
		code.append("-->\r\n");
		return code.toString();
	}
}