/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     2013-11-18 15:23:50                          */
/*==============================================================*/


DROP TABLE OA_INSPECT_BASEINFO CASCADE CONSTRAINTS;

DROP TABLE OA_INSPECT_RECEPT CASCADE CONSTRAINTS;

DROP TABLE OA_INSPECT_RECEPTUSER CASCADE CONSTRAINTS;

DROP TABLE OA_INSPECT_TYPE CASCADE CONSTRAINTS;

DROP TABLE "OA_INSPECT_RESPONSE" CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_INSPECT_BASEINFO                                   */
/*==============================================================*/
CREATE TABLE OA_INSPECT_BASEINFO 
(
   INFO_ID              VARCHAR2(50)         NOT NULL,
   INSPECT_NAME         VARCHAR2(400),
   INSPECT_TYPE         VARCHAR2(50),
   CONTENT              CLOB,
   INSPECT_STATE        VARCHAR2(10),
   "CREATE_TIME"        DATE,
   SEND_TIME            DATE,
   "PLAN_ENDTIME"       DATE,
   "REMIND_TIME"        DATE,
   "REMIND_CONTENT"     VARCHAR(500),
   RECEPT_ORGIDS        VARCHAR2(4000),
   RECEPT_ORGNAMES      VARCHAR2(4000),
   SEND_USER_ID         VARCHAR2(50),
   "SEND_USER_NAME"     VARCHAR2(50),
   "USER_ORGID"         VARCHAR2(50),
   "USER_ORGNAME"       VARCHAR2(200),
   ATTACH_ID            VARCHAR2(50),
   IS_SMS               VARCHAR2(2),
   IS_MSG               VARCHAR2(2),
   IS_RTX               VARCHAR2(2),
   IS_MAIL              VARCHAR2(2),
   "IS_REPORT"          VARCHAR2(2),
   CONSTRAINT PK_OA_INSPECT_BASEINFO PRIMARY KEY (INFO_ID)
);

COMMENT ON TABLE OA_INSPECT_BASEINFO IS
'督查督办基本信息表';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.INFO_ID IS
'信息主键';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.INSPECT_NAME IS
'名称';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.INSPECT_TYPE IS
'任务类型';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.CONTENT IS
'正文';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.INSPECT_STATE IS
'状态';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."CREATE_TIME" IS
'任务创建时间';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.SEND_TIME IS
'交办时间';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."PLAN_ENDTIME" IS
'指定完成期限';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."REMIND_TIME" IS
'催办提醒时间';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."REMIND_CONTENT" IS
'催办提醒内容';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.RECEPT_ORGIDS IS
'办理单位id集合';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.RECEPT_ORGNAMES IS
'办理单位名称集合';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.SEND_USER_ID IS
'发起人id';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."SEND_USER_NAME" IS
'发起人姓名';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."USER_ORGID" IS
'用户所在单位id';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."USER_ORGNAME" IS
'用户所在单位名称';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.ATTACH_ID IS
'与附件表的关联id';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.IS_SMS IS
'是否短信(1是,0否)';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.IS_MSG IS
'是否站内消息(1是,0否)';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.IS_RTX IS
'是否及时消息(1是,0否)';

COMMENT ON COLUMN OA_INSPECT_BASEINFO.IS_MAIL IS
'是否邮件(1是,0否)';

COMMENT ON COLUMN OA_INSPECT_BASEINFO."IS_REPORT" IS
'是否上报(1是，其他否)';

/*==============================================================*/
/* Table: OA_INSPECT_RECEPT                                     */
/*==============================================================*/
CREATE TABLE OA_INSPECT_RECEPT 
(
   RECEPT_ID            VARCHAR2(50)         NOT NULL,
   INFO_ID              VARCHAR2(50),
   RECEPT_STATE         VARCHAR2(10),
   RECEPT_TIME          DATE,
   ORG_ID               VARCHAR2(50),
   ORG_NAME             VARCHAR2(200),
   "CARD"               VARCHAR2(10),
   "RESPONSE_TIME"      DATE,
   CONSTRAINT PK_OA_INSPECT_RECEPT PRIMARY KEY (RECEPT_ID)
);

COMMENT ON TABLE OA_INSPECT_RECEPT IS
'督查督办通知接收表';

COMMENT ON COLUMN OA_INSPECT_RECEPT.RECEPT_ID IS
'接收主键';

COMMENT ON COLUMN OA_INSPECT_RECEPT.INFO_ID IS
'信息主键';

COMMENT ON COLUMN OA_INSPECT_RECEPT.RECEPT_STATE IS
'状态（0：未反馈，1：已反馈，2：退回重办）';

COMMENT ON COLUMN OA_INSPECT_RECEPT.RECEPT_TIME IS
'接收时间';

COMMENT ON COLUMN OA_INSPECT_RECEPT.ORG_ID IS
'接收单位id';

COMMENT ON COLUMN OA_INSPECT_RECEPT.ORG_NAME IS
'接收单位名称';

COMMENT ON COLUMN OA_INSPECT_RECEPT."CARD" IS
'发牌（即对任务完成状况的评价）';

COMMENT ON COLUMN OA_INSPECT_RECEPT."RESPONSE_TIME" IS
'反馈时间（根据反馈表的情况动态修改）';

/*==============================================================*/
/* Table: OA_INSPECT_RECEPTUSER                                 */
/*==============================================================*/
CREATE TABLE OA_INSPECT_RECEPTUSER 
(
   "ID"                 VARCHAR2(50)         NOT NULL,
   RECEPT_ID            VARCHAR2(50),
   "RECEPT_USERID"      VARCHAR2(50),
   "RECEPT_USERNAME"    VARCHAR2(50),
   "PHONE"              VARCHAR2(50),
   "EMAIL"              VARCHAR2(200),
   "TEMP"               VARCHAR2(100),
   "INFO_ID"            VARCHAR2(50),
   CONSTRAINT PK_OA_INSPECT_RECEPTUSER PRIMARY KEY ("ID")
);

COMMENT ON TABLE OA_INSPECT_RECEPTUSER IS
'督查督办通知接收用户表（防止一个单位配置多个用户而采用）';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."ID" IS
'主键';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER.RECEPT_ID IS
'接收主键';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."RECEPT_USERID" IS
'接收人id';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."RECEPT_USERNAME" IS
'接收人姓名';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."PHONE" IS
'接收人电话号码';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."EMAIL" IS
'接收人个人邮箱（预留字段）';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."TEMP" IS
'备用字段';

COMMENT ON COLUMN OA_INSPECT_RECEPTUSER."INFO_ID" IS
'任务id';

/*==============================================================*/
/* Table: OA_INSPECT_TYPE                                       */
/*==============================================================*/
CREATE TABLE OA_INSPECT_TYPE 
(
   TYPE_ID              VARCHAR2(50)         NOT NULL,
   TYPE_NAME            VARCHAR2(50),
   TYPE_REMARK          VARCHAR2(500),
   TYPE_TEMPLATE        CLOB,
   "TYPE_ORDER"         NUMBER,
   CONSTRAINT PK_OA_INSPECT_TYPE PRIMARY KEY (TYPE_ID)
);

COMMENT ON TABLE OA_INSPECT_TYPE IS
'督查督办任务类别表';

COMMENT ON COLUMN OA_INSPECT_TYPE.TYPE_ID IS
'类别主键';

COMMENT ON COLUMN OA_INSPECT_TYPE.TYPE_NAME IS
'类别名称';

COMMENT ON COLUMN OA_INSPECT_TYPE.TYPE_REMARK IS
'说明';

COMMENT ON COLUMN OA_INSPECT_TYPE.TYPE_TEMPLATE IS
'督办内容模板';

COMMENT ON COLUMN OA_INSPECT_TYPE."TYPE_ORDER" IS
'排序号';

/*==============================================================*/
/* Table: "OA_INSPECT_RESPONSE"                                 */
/*==============================================================*/
CREATE TABLE "OA_INSPECT_RESPONSE" 
(
   "RESPONSE_ID"        VARCHAR2(50)         NOT NULL,
   RECEPT_ID            VARCHAR2(50),
   "RESPONSE_CONTENT"   CLOB,
   "RESPONSE_USERID"    VARCHAR2(50),
   "RESPONSE_USERNAME"  VARCHAR2(50),
   ORG_ID               VARCHAR2(50),
   ORG_NAME             VARCHAR2(200),
   "RESPONSE_STATE"     VARCHAR2(10),
   "RESPONSE_TIME"      DATE,
   "TYPE"               VARCHAR2(10),
   "INFO_ID"            VARCHAR2(50),
   "ATTACH_ID"          VARCHAR2(50),
   CONSTRAINT PK_OA_INSPECT_RESPONSE PRIMARY KEY ("RESPONSE_ID")
);

COMMENT ON TABLE "OA_INSPECT_RESPONSE" IS
'督查督办任务反馈表';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."RESPONSE_ID" IS
'接收主键';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE".RECEPT_ID IS
'信息主键';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."RESPONSE_CONTENT" IS
'反馈内容';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."RESPONSE_USERID" IS
'反馈人id';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."RESPONSE_USERNAME" IS
'反馈人姓名';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE".ORG_ID IS
'接收单位id';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE".ORG_NAME IS
'接收单位名称';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."RESPONSE_STATE" IS
'阅读状态(0:未读,1:已读)';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."RESPONSE_TIME" IS
'反馈时间';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."TYPE" IS
'类别(0:反馈信息，1：退回重办信息)';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."INFO_ID" IS
'任务id';

COMMENT ON COLUMN "OA_INSPECT_RESPONSE"."ATTACH_ID" IS
'附件id';

