ALTER TABLE OA_TASK_TASKREPORT
   DROP CONSTRAINT FK_OA_TA_REFERENCE_OA_T1;

DROP TABLE OA_TASK_BASEINFO CASCADE CONSTRAINTS;

DROP TABLE OA_TASK_TASKREPORT CASCADE CONSTRAINTS;

DROP TABLE OA_TASK_TYPE CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_TASK_BASEINFO                                      */
/*==============================================================*/
CREATE TABLE OA_TASK_BASEINFO 
(
   ID                   VARCHAR2(50)         NOT NULL,
   TASK_NAME            VARCHAR2(300)        NOT NULL,
   START_TIME           DATE,
   END_TIME             DATE,
   HIGHER_LEVEL_TASK    VARCHAR2(50),
   TASK_CONTENT         CLOB,
   DEGREE_OF_IMPORTANCE VARCHAR2(50),
   COMPLETION_RATE      VARCHAR2(10),
   TASK_TYPE            VARCHAR2(50),
   ATTACH_ID            VARCHAR2(50),
   TASK_STATUS          VARCHAR2(50),
   INPUT_USERID         VARCHAR2(50),
   INPUT_ORGID          VARCHAR2(40),
   DEL_IDENT            VARCHAR2(10),
   INPUT_USERNAME       VARCHAR2(50),
   INPUT_ORGNAME        VARCHAR2(200),
   RECEIVE_USERID       VARCHAR2(50),
   RECEIVE_USERNAME     VARCHAR2(50),
   RECEIVE_ORGID        VARCHAR2(50),
   RECEIVE_ORGNAME      VARCHAR2(200),
   CONSTRAINT PK_OA_TASKSASSIGNED_BASEINF PRIMARY KEY (ID)
);

COMMENT ON TABLE OA_TASK_BASEINFO IS
'任务交办基本信息表';

COMMENT ON COLUMN OA_TASK_BASEINFO.ID IS
'id';

COMMENT ON COLUMN OA_TASK_BASEINFO.TASK_NAME IS
'类型名称';

COMMENT ON COLUMN OA_TASK_BASEINFO.START_TIME IS
'开始时间';

COMMENT ON COLUMN OA_TASK_BASEINFO.END_TIME IS
'结束时间';

COMMENT ON COLUMN OA_TASK_BASEINFO.HIGHER_LEVEL_TASK IS
'上级任务';

COMMENT ON COLUMN OA_TASK_BASEINFO.TASK_CONTENT IS
'内容';

COMMENT ON COLUMN OA_TASK_BASEINFO.DEGREE_OF_IMPORTANCE IS
'重要程度';

COMMENT ON COLUMN OA_TASK_BASEINFO.COMPLETION_RATE IS
'完成率';

COMMENT ON COLUMN OA_TASK_BASEINFO.TASK_TYPE IS
'任务类型';

COMMENT ON COLUMN OA_TASK_BASEINFO.ATTACH_ID IS
'附件id';

COMMENT ON COLUMN OA_TASK_BASEINFO.TASK_STATUS IS
'任务状态  未办理(1) ,办理中 (2),已办结(3)';

COMMENT ON COLUMN OA_TASK_BASEINFO.INPUT_USERID IS
'录入用户id';

COMMENT ON COLUMN OA_TASK_BASEINFO.INPUT_ORGID IS
'录入机构id';

COMMENT ON COLUMN OA_TASK_BASEINFO.DEL_IDENT IS
'逻辑删除标识：1：逻辑删除';

COMMENT ON COLUMN OA_TASK_BASEINFO.INPUT_USERNAME IS
'录入用户名';

COMMENT ON COLUMN OA_TASK_BASEINFO.INPUT_ORGNAME IS
'录入机构名';

COMMENT ON COLUMN OA_TASK_BASEINFO.RECEIVE_USERID IS
'任务接收人（负责人）id';

COMMENT ON COLUMN OA_TASK_BASEINFO.RECEIVE_USERNAME IS
'任务接收人姓名';

COMMENT ON COLUMN OA_TASK_BASEINFO.RECEIVE_ORGID IS
'任务接收单位id';

COMMENT ON COLUMN OA_TASK_BASEINFO.RECEIVE_ORGNAME IS
'任务接收单位名';

/*==============================================================*/
/* Table: OA_TASK_TASKREPORT                                    */
/*==============================================================*/
CREATE TABLE OA_TASK_TASKREPORT 
(
   ID                   VARCHAR2(50)         NOT NULL,
   TASK_ID              VARCHAR2(50),
   REPORT_CONTENT       CLOB,
   REPORT_TIME          DATE,
   ATTACH_ID            VARCHAR2(50),
   USER_ID              VARCHAR2(50),
   USER_NAME            VARCHAR2(50),
   TYPE                 VARCHAR2(50),
   CONSTRAINT PK_OA_TASKSASSIGNED_TASKREP PRIMARY KEY (ID)
);

COMMENT ON TABLE OA_TASK_TASKREPORT IS
'任务交办任务汇报表';

COMMENT ON COLUMN OA_TASK_TASKREPORT.TASK_ID IS
'任务交_主键';

COMMENT ON COLUMN OA_TASK_TASKREPORT.REPORT_CONTENT IS
'汇报内容';

COMMENT ON COLUMN OA_TASK_TASKREPORT.REPORT_TIME IS
'汇报时间';

COMMENT ON COLUMN OA_TASK_TASKREPORT.ATTACH_ID IS
'附件id';

COMMENT ON COLUMN OA_TASK_TASKREPORT.USER_ID IS
'用户id';

COMMENT ON COLUMN OA_TASK_TASKREPORT.USER_NAME IS
'用户id';

COMMENT ON COLUMN OA_TASK_TASKREPORT.TYPE IS
'回复任务状态 0:未读 1：已读';

/*==============================================================*/
/* Table: OA_TASK_TYPE                                          */
/*==============================================================*/
CREATE TABLE OA_TASK_TYPE 
(
   TYPE_ID              VARCHAR2(50)         NOT NULL,
   TYPE_NAME            VARCHAR2(200)        NOT NULL,
   TYPE_SORT            VARCHAR2(50)         NOT NULL,
   TYPE_VALUE           VARCHAR2(50),
   CONSTRAINT PK_OA_TASK_TYPE PRIMARY KEY (TYPE_ID)
);

COMMENT ON TABLE OA_TASK_TYPE IS
'任务交办类型字典表';

COMMENT ON COLUMN OA_TASK_TYPE.TYPE_NAME IS
'类型名称';

COMMENT ON COLUMN OA_TASK_TYPE.TYPE_SORT IS
'类型分类';

COMMENT ON COLUMN OA_TASK_TYPE.TYPE_VALUE IS
'类型value';

ALTER TABLE OA_TASK_TASKREPORT
   ADD CONSTRAINT FK_OA_TA_REFERENCE_OA_T1 FOREIGN KEY (TASK_ID)
      REFERENCES OA_TASK_BASEINFO (ID);
