CREATE OR REPLACE FUNCTION OA_GETALLACTION_INDEX(V_INS_ID IN VARCHAR2,
                                              V_FLOW_ACTIONID IN VARCHAR2)
--根据流程实例ID，环节活动ID 按照时间查询出顺序。
  RETURN VARCHAR2 AS
  ACT_INDEX VARCHAR2(50);
BEGIN
  SELECT ACT_INDEX
    INTO ACT_INDEX
    FROM (SELECT ROW_NUMBER() OVER(ORDER BY W.TACHE_BEGIN_TIME DESC) ACT_INDEX,
                 W.FLOW_ACTION_ID
            FROM OA_FLOW_INSWFACTION W
           WHERE W.INS_ID = V_INS_ID
             AND W.IS_VALID = 'Y' )
   WHERE FLOW_ACTION_ID = V_FLOW_ACTIONID;
  RETURN(ACT_INDEX);
END;
