DROP TABLE OA_FLOW_DOCUMENT_FILE CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_FLOW_DOCUMENT_FILE                                 */
/*==============================================================*/
CREATE TABLE OA_FLOW_DOCUMENT_FILE 
(
   ID                   VARCHAR2(50)         NOT NULL,
   INS_ID               VARCHAR2(50),
   ACTION_ID            VARCHAR2(50),
   FLOW_ACT_ID          VARCHAR2(50),
   FILETYPE             VARCHAR2(10),
   FILESIZE             NUMBER(10),
   FILEDATE             DATE,
   FILEBODY             BLOB,
   FILEPATH             VARCHAR2(128),
   USERNAME             VARCHAR2(64),
   DESCRIPT             VARCHAR2(255)
);

COMMENT ON TABLE OA_FLOW_DOCUMENT_FILE IS
'流程环节正文备份表';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.ID IS
'主键ID';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.INS_ID IS
'流程实例ID';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.ACTION_ID IS
'环节ID';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.FLOW_ACT_ID IS
'流程环节实例ID';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.FILETYPE IS
'文件类型';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.FILESIZE IS
'文件大小';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.FILEDATE IS
'文件日期';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.FILEBODY IS
'正文';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.FILEPATH IS
'文件路径';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.USERNAME IS
'用户名';

COMMENT ON COLUMN OA_FLOW_DOCUMENT_FILE.DESCRIPT IS
'说明';
