DROP TABLE OA_ARCHIVE_DISPATCH CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_ARCHIVE_DISPATCH                                   */
/*==============================================================*/
CREATE TABLE OA_ARCHIVE_DISPATCH 
(
   ID                   VARCHAR2(50)         NOT NULL,
   BUSI_ID              VARCHAR2(50),
   INS_ID               VARCHAR2(50),
   TITLE                VARCHAR2(200),
   CAPTION              VARCHAR2(200),
   URGENCY_GRADE        VARCHAR2(200),
   ARCHIVE_NO           VARCHAR2(200),
   DISPATCH_TYPE        VARCHAR2(50),
   KEY_WORD             VARCHAR2(50),
   EFFECT_DATE          VARCHAR2(50),
   SENDER               VARCHAR2(50),
   SECRECY_GRADE        VARCHAR2(50),
   SEND_ORG_ID          VARCHAR2(50),
   SEND_ORG_ADDR        VARCHAR2(50),
   SEND_ORG_NAME        VARCHAR2(200),
   SEND_ATTACH_ID       VARCHAR2(50),
   CREATE_DATE          DATE,
   IS_SNED_ATTACH       VARCHAR2(50),
   ISDXTX               VARCHAR2(50),
   MSG_TXT              VARCHAR2(500),
   UNION_ARCHIVE        VARCHAR2(50),
   REMARK1              VARCHAR2(50),
   REMARK2              VARCHAR2(50),
   CONSTRAINT PK_OA_ARCHIVE_DISPATCH PRIMARY KEY (ID)
);

COMMENT ON TABLE OA_ARCHIVE_DISPATCH IS
'公文发送端,公文要素表';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.ID IS
'主键ID';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.BUSI_ID IS
'业务ID';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.INS_ID IS
'流程实例ID';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.TITLE IS
'公文标题';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.CAPTION IS
'主题词';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.URGENCY_GRADE IS
'紧急程度';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.ARCHIVE_NO IS
'发文号';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.DISPATCH_TYPE IS
'文种';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.KEY_WORD IS
'关键字';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.EFFECT_DATE IS
'保密期限';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.SENDER IS
'签发人';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.SECRECY_GRADE IS
'公文密级';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.SEND_ORG_ID IS
'分发单位ID';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.SEND_ORG_ADDR IS
'分发单位机构地址码';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.SEND_ORG_NAME IS
'分发单位名称';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.SEND_ATTACH_ID IS
'分发单位附件';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.CREATE_DATE IS
'成文日期';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.IS_SNED_ATTACH IS
'正文附件是否分发';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.ISDXTX IS
'是否发送短信';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.MSG_TXT IS
'短信内容';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.UNION_ARCHIVE IS
'是否联合发文';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.REMARK1 IS
'保留字段1';

COMMENT ON COLUMN OA_ARCHIVE_DISPATCH.REMARK2 IS
'保留字段2';

DROP TABLE OA_CEB_WORD CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: OA_CEB_WORD                                           */
/*==============================================================*/
CREATE TABLE OA_CEB_WORD 
(
   INS_ID               VARCHAR2(50)         NOT NULL,
   CEB_ID               VARCHAR2(50),
   CREAT_DATE           DATE,
   CEB_TEXT             CLOB,
   REMARK1              VARCHAR2(200),
   CONSTRAINT PK_OA_CEB_WORD PRIMARY KEY (INS_ID)
);

COMMENT ON TABLE OA_CEB_WORD IS
'保存盖章后的CEB文件';

COMMENT ON COLUMN OA_CEB_WORD.INS_ID IS
'流程实例ID';

COMMENT ON COLUMN OA_CEB_WORD.CEB_ID IS
'公文传输系统UUID';

COMMENT ON COLUMN OA_CEB_WORD.CREAT_DATE IS
'创建日期';

COMMENT ON COLUMN OA_CEB_WORD.CEB_TEXT IS
'CEB正文';

COMMENT ON COLUMN OA_CEB_WORD.REMARK1 IS
'扩展字段';
